
<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insert sample data into foods table
        DB::table('foods')->insert([



            ['name' => '5 A Day Salad','foodcategory_id'=> 7],
            ['name' => 'Any Days a Picnic Chicken Salad','foodcategory_id'=> 7],
            ['name' => 'Apple & Chicken Salad','foodcategory_id'=> 7],
            ['name' => 'Apple Banana Salad with Peanuts','foodcategory_id'=> 7],
            ['name' => 'Apple Coleslaw','foodcategory_id'=> 7],
            ['name' => 'Apple Cranberry Salad Toss','foodcategory_id'=> 7],
            ['name' => 'Apple Salad','foodcategory_id'=> 7],
            ['name' => 'Apple Salad with Sweet & Tangy Yogurt Dressing','foodcategory_id'=> 7],
            ['name' => 'Avocado, Potato, and Grilled Chicken Salad','foodcategory_id'=> 7],
            ['name' => 'Banana Waldorf','foodcategory_id'=> 7],
            ['name' => 'Beet & White Bean Salad','foodcategory_id'=> 7],
            ['name' => 'Beets, Beans, and Greens','foodcategory_id'=> 7],
            ['name' => 'Bell Pepper and Apple Coleslaw','foodcategory_id'=> 7],
            ['name' => 'Bell Pepper and Potato Salad','foodcategory_id'=> 7],
            ['name' => 'Broccoli Salad','foodcategory_id'=> 7],
            ['name' => 'Brussel Sprouts, Cranberry, and Bulgur Salad','foodcategory_id'=> 7],
            ['name' => 'Bulgur Chickpea Salad','foodcategory_id'=> 7],
            ['name' => 'Cabbage Salad','foodcategory_id'=> 7],
            ['name' => 'Caribbean Bean Salad','foodcategory_id'=> 7],
            ['name' => 'Carrot Raisin Salad','foodcategory_id'=> 7],
            ['name' => 'Cherry, Melon, & Grape Salad','foodcategory_id'=> 7],
            ['name' => 'Chicken and Cranberry Salad','foodcategory_id'=> 7],
            ['name' => 'Chicken Club Salad','foodcategory_id'=> 7],
            ['name' => 'Chicken Pasta Salad','foodcategory_id'=> 7],
            ['name' => 'Chicken Rice Salad','foodcategory_id'=> 7],
            ['name' => 'Chicken Salad with Ramen Noodles','foodcategory_id'=> 7],
            ['name' => 'Chicken Waldorf Salad','foodcategory_id'=> 7],
            ['name' => 'Chicken, Rice, and Fruit Salad','foodcategory_id'=> 7],
            ['name' => 'Citrus Salad','foodcategory_id'=> 7],
            ['name' => 'Cobb Salad with Pears','foodcategory_id'=> 7],
            ['name' => 'Confetti Grain Salad','foodcategory_id'=> 7],
            ['name' => 'Confetti Slaw','foodcategory_id'=> 7],
            ['name' => 'Corn and Bean Medley','foodcategory_id'=> 7],
            ['name' => 'Corn and Green Chili Salad','foodcategory_id'=> 7],
            ['name' => 'Corn Salad with Fat-free Ranch Dressing','foodcategory_id'=> 7],
            ['name' => 'Corn Salad with Fresh Basil and Lemon','foodcategory_id'=> 7],
            ['name' => 'Corn, Blueberry, and Wild Rice Salad','foodcategory_id'=> 7],
            ['name' => 'Country Style Potato Salad','foodcategory_id'=> 7],
            ['name' => 'Cranberry Salad','foodcategory_id'=> 7],
            ['name' => 'Crunchy Chicken Salad','foodcategory_id'=> 7],
            ['name' => 'Cuban Salad','foodcategory_id'=> 7],
            ['name' => 'Cucumber Blueberry Salad','foodcategory_id'=> 7],
            ['name' => 'Cucumber Salad','foodcategory_id'=> 7],
            ['name' => 'Cucumber Salad with Tomatoes','foodcategory_id'=> 7],
            ['name' => 'Curried Chicken Salad','foodcategory_id'=> 7],
            ['name' => 'Curried Chickpea Salad','foodcategory_id'=> 7],
            ['name' => 'Curtido Salvadoreño (Cabbage Salad)','foodcategory_id'=> 7],
            ['name' => 'Egg Salad','foodcategory_id'=> 7],
            ['name' => 'European Salad','foodcategory_id'=> 7],
            ['name' => 'Fiesta Rice Salad','foodcategory_id'=> 7],
            ['name' => 'Fruit & Feta Salad','foodcategory_id'=> 7],
            ['name' => 'Fruit Cole Slaw','foodcategory_id'=> 7],
            ['name' => 'Fruit Salad','foodcategory_id'=> 7],
            ['name' => 'Fruit Salad with Jicama','foodcategory_id'=> 7],
            ['name' => 'Garden Cannellini Bean Salad','foodcategory_id'=> 7],
            ['name' => 'Garden Orchard Salad','foodcategory_id'=> 7],
            ['name' => 'Gingery Quinoa with Green Beans','foodcategory_id'=> 7],
            ['name' => 'Grape and Cashew Salad Sandwich','foodcategory_id'=> 7],
            ['name' => 'Grapefruit Spinach Salad','foodcategory_id'=> 7],
            ['name' => 'Greek Salad','foodcategory_id'=> 7],
            ['name' => 'Greek Salad with Chicken','foodcategory_id'=> 7],
            ['name' => 'Green Beans and New Potatoes','foodcategory_id'=> 7],
            ['name' => 'Grilled Asparagus and Shrimp Quinoa Salad with Lemon Vinaigrette','foodcategory_id'=> 7],
            ['name' => 'Grilled Lamb Salad','foodcategory_id'=> 7],
            ['name' => 'Harvest Vegetable Salad','foodcategory_id'=> 7],
            ['name' => 'Hearty Vegetable Salad with Herb Dressing','foodcategory_id'=> 7],
            ['name' => 'Herb Potato Salad','foodcategory_id'=> 7],
            ['name' => 'Homemade Ranch Dressing','foodcategory_id'=> 7],
            ['name' => 'Italian Pasta Salad','foodcategory_id'=> 7],
            ['name' => 'Kale Salad with Yogurt Dressing','foodcategory_id'=> 7],
            ['name' => 'Kale with Nuts and Raisins','foodcategory_id'=> 7],
            ['name' => 'Leaf Finger Salad','foodcategory_id'=> 7],
            ['name' => 'Lentil Vegetable Salad','foodcategory_id'=> 7],
            ['name' => 'Magical Fruit Salad','foodcategory_id'=> 7],
            ['name' => 'Main Dish Salad','foodcategory_id'=> 7],
            ['name' => 'Mango Berry Rotini Salad','foodcategory_id'=> 7],
            ['name' => 'Marinated Three-Bean Salad','foodcategory_id'=> 7],
            ['name' => 'Mediterranean Chicken and White Bean Salad','foodcategory_id'=> 7],
            ['name' => 'Mediterranean Tuna Antipasti Salad','foodcategory_id'=> 7],
            ['name' => 'Mixed Fruit Salad','foodcategory_id'=> 7],
            ['name' => 'Pasta Primavera Salad','foodcategory_id'=> 7],
            ['name' => 'Pasta Salad','foodcategory_id'=> 7],
            ['name' => 'Pasta Salad with Herb Vinaigrette','foodcategory_id'=> 7],
            ['name' => 'Pineapple Avocado Chicken Salad','foodcategory_id'=> 7],
            ['name' => 'Pink Party Salad','foodcategory_id'=> 7],
            ['name' => 'Potato Salad','foodcategory_id'=> 7],
            ['name' => 'Potato Salad','foodcategory_id'=> 7],
            ['name' => 'Quick N Cool Summer Salad','foodcategory_id'=> 7],
            ['name' => 'Quick and Easy Baked Potato Salad','foodcategory_id'=> 7],
            ['name' => 'Quick Black Bean Salad','foodcategory_id'=> 7],
            ['name' => 'Quinoa and Black Bean Salad','foodcategory_id'=> 7],
            ['name' => 'Rainbow Veggie Salad','foodcategory_id'=> 7],
            ['name' => 'Red Potato Salad','foodcategory_id'=> 7],
            ['name' => 'Roasted Chickpeas (Garbanzo Beans)','foodcategory_id'=> 7],
            ['name' => 'Salad with Pineapple, Nuts, and Raisins','foodcategory_id'=> 7],
            ['name' => 'Sanchico Tuna Salad','foodcategory_id'=> 7],
            ['name' => 'Shrimp Confetti Salad Sandwich with Grapes','foodcategory_id'=> 7],
            ['name' => 'Simply Satisfying Kale and Tuna Salad','foodcategory_id'=> 7],
            ['name' => 'Snappy Cole Slaw','foodcategory_id'=> 7],
            ['name' => 'Somali Summer Salad','foodcategory_id'=> 7],
            ['name' => 'South of the Border Salad','foodcategory_id'=> 7],
            ['name' => 'Spicy Cucumber & Orange Salad','foodcategory_id'=> 7],
            ['name' => 'Spinach Black Bean Salad','foodcategory_id'=> 7],
            ['name' => 'Spinach Rice Salad','foodcategory_id'=> 7],
            ['name' => 'Spinach Salad with Apples and Eggs','foodcategory_id'=> 7],
            ['name' => 'Spinach Salad with Apples and Raisins','foodcategory_id'=> 7],
            ['name' => 'Splendid Fruit Salad','foodcategory_id'=> 7],
            ['name' => 'Summer Fruit Salad','foodcategory_id'=> 7],
            ['name' => 'Summer Salad','foodcategory_id'=> 7],
            ['name' => 'Sunshine Salad','foodcategory_id'=> 7],
            ['name' => 'Sweet Potato Harvest Salad','foodcategory_id'=> 7],
            ['name' => 'Taco Salad','foodcategory_id'=> 7],
            ['name' => 'Taco Salad II','foodcategory_id'=> 7],
            ['name' => 'Tangy Crisp Vegetable and Pasta Salad','foodcategory_id'=> 7],
            ['name' => 'The Perfect "Pear" and Brussels Sprout Salad','foodcategory_id'=> 7],
            ['name' => 'Three Bean Salad','foodcategory_id'=> 7],
            ['name' => 'Tofu Salad','foodcategory_id'=> 7],
            ['name' => 'Tomato and Cucumber Salad','foodcategory_id'=> 7],
            ['name' => 'Tomato Basil and Bean Pasta Salad','foodcategory_id'=> 7],
            ['name' => 'Tuna Apple Salad','foodcategory_id'=> 7],
            ['name' => 'Tuna Apple Salad Sandwich','foodcategory_id'=> 7],
            ['name' => 'Tuna Salad with Grapes','foodcategory_id'=> 7],
            ['name' => 'Turkey Potato Salad','foodcategory_id'=> 7],
            ['name' => 'Turkey Salad with Orange Vinaigrette','foodcategory_id'=> 7],
            ['name' => 'Vegetable Salad','foodcategory_id'=> 7],
            ['name' => 'Vidalia Onion and Tomato Salad with Grilled Tuna','foodcategory_id'=> 7],
            ['name' => 'Zesty Citrus Coleslaw','foodcategory_id'=> 7],
            ['name' => 'Zesty Pasta Primavera Salad','foodcategory_id'=> 7],



            ['name' => '','foodcategory_id'=> 8],
            ['name' => 'Asian Mango Chicken Wraps','foodcategory_id'=> 8],
            ['name' => 'Chicken Apple Salad Sandwich','foodcategory_id'=> 8],
            ['name' => 'Chicken Salad and Peach Sandwich','foodcategory_id'=> 8],
            ['name' => 'Curried Chickpea Salad','foodcategory_id'=> 8],
            ['name' => 'Egg Salad','foodcategory_id'=> 8],
            ['name' => 'Falafel with Yogurt Sandwich','foodcategory_id'=> 8],
            ['name' => 'Fruity Thai Pita Pockets','foodcategory_id'=> 8],
            ['name' => 'Grape and Cashew Salad Sandwich','foodcategory_id'=> 8],
            ['name' => 'Grilled Cheese with Peaches','foodcategory_id'=> 8],
            ['name' => 'Peanut Butter and Apple Wraps','foodcategory_id'=> 8],
            ['name' => 'Peanut, Peach, N Pineapple Wrap','foodcategory_id'=> 8],
            ['name' => 'Shrimp Confetti Salad Sandwich with Grapes','foodcategory_id'=> 8],
            ['name' => 'Tuna Apple Salad','foodcategory_id'=> 8],
            ['name' => 'Tuna Apple Salad Sandwich','foodcategory_id'=> 8],
            ['name' => 'Tuna Slider with Green Chiles','foodcategory_id'=> 8],
            ['name' => 'Tuna Veggie Picnic Sandwich','foodcategory_id'=> 8],
            ['name' => 'Turkey and Cucumber Sandwich','foodcategory_id'=> 8],
            ['name' => 'Veggie Bean Wrap','foodcategory_id'=> 8],


            ['name' => 'Argentinian Chimichurri Sauce','foodcategory_id'=> 9],
            ['name' => 'Avocado and Corn Salsa','foodcategory_id'=> 9],
            ['name' => 'Basic Soup and Sauce Mix','foodcategory_id'=> 9],
            ['name' => 'Bean Dip','foodcategory_id'=> 9],
            ['name' => 'Brussels Sprouts with Mushroom Sauce','foodcategory_id'=> 9],
            ['name' => 'Caramel Sauce','foodcategory_id'=> 9],
            ['name' => 'Chickpea Dip','foodcategory_id'=> 9],
            ['name' => 'Chili and Spice Seasoning','foodcategory_id'=> 9],
            ['name' => 'Chili Bean Dip','foodcategory_id'=> 9],
            ['name' => 'Confetti Bean Salsa','foodcategory_id'=> 9],
            ['name' => 'Creamy Dill Dip','foodcategory_id'=> 9],
            ['name' => 'Creamy Italian Herb Dressing','foodcategory_id'=> 9],
            ['name' => 'Creamy Peanut Dip','foodcategory_id'=> 9],
            ['name' => 'Cucumber Yogurt and Cream Cheese Dip','foodcategory_id'=> 9],
            ['name' => 'Cucumber, Yogurt and Herb Dip','foodcategory_id'=> 9],
            ['name' => 'Curry Dip','foodcategory_id'=> 9],
            ['name' => 'Curry Vegetable Dip','foodcategory_id'=> 9],
            ['name' => 'Eating Smart Seasoning Mix','foodcategory_id'=> 9],
            ['name' => 'Eggplant and Pepper Dip','foodcategory_id'=> 9],
            ['name' => 'Farmers Market Salsa','foodcategory_id'=> 9],
            ['name' => 'Fiesta Hummus','foodcategory_id'=> 9],
            ['name' => 'French Salad Dressing','foodcategory_id'=> 9],
            ['name' => 'Fresh Salsa','foodcategory_id'=> 9],
            ['name' => 'Fresh Tomato Salsa','foodcategory_id'=> 9],
            ['name' => 'Fresh Tomato Sauce','foodcategory_id'=> 9],
            ['name' => 'Fruit Dip','foodcategory_id'=> 9],
            ['name' => 'Grape Salsa','foodcategory_id'=> 9],
            ['name' => 'Herbed Dip','foodcategory_id'=> 9],
            ['name' => 'Homemade Cranberry Sauce','foodcategory_id'=> 9],
            ['name' => 'Homemade Ranch Dressing','foodcategory_id'=> 9],
            ['name' => 'Honey Mustard Dressing','foodcategory_id'=> 9],
            ['name' => 'Hot N Spicy Seasoning','foodcategory_id'=> 9],
            ['name' => 'Hummus','foodcategory_id'=> 9],
            ['name' => 'Lite Italian Dressing','foodcategory_id'=> 9],
            ['name' => 'Low Calorie Dressing','foodcategory_id'=> 9],
            ['name' => 'Low Fat Creamy Dressing','foodcategory_id'=> 9],
            ['name' => 'Low Fat Ranch Dip','foodcategory_id'=> 9],
            ['name' => 'Low-Fat Tartar Sauce','foodcategory_id'=> 9],
            ['name' => 'Mango Salsa','foodcategory_id'=> 9],
            ['name' => 'Marinara Sauce','foodcategory_id'=> 9],
            ['name' => 'Melon Salsa','foodcategory_id'=> 9],
            ['name' => 'Mock Sour Cream','foodcategory_id'=> 9],
            ['name' => 'Parsley, Almond, and Lemon Pesto','foodcategory_id'=> 9],
            ['name' => 'Pasta with Vegetables','foodcategory_id'=> 9],
            ['name' => 'Pea Guacamole','foodcategory_id'=> 9],
            ['name' => 'Pea Pesto','foodcategory_id'=> 9],
            ['name' => 'Peach Sauce','foodcategory_id'=> 9],
            ['name' => 'Pico de Gallo','foodcategory_id'=> 9],
            ['name' => 'Salt-free All Purpose Blend','foodcategory_id'=> 9],
            ['name' => 'South of the Border Dip','foodcategory_id'=> 9],
            ['name' => 'Squash Salsa','foodcategory_id'=> 9],
            ['name' => 'Sweet and Savory Peanut Butter Dip','foodcategory_id'=> 9],
            ['name' => 'Sweet and Sour Dressing','foodcategory_id'=> 9],
            ['name' => 'Sweet and Sour Salad Dressing','foodcategory_id'=> 9],
            ['name' => 'Sweetened Condensed Milk','foodcategory_id'=> 9],
            ['name' => 'Tangy Dressing','foodcategory_id'=> 9],
            ['name' => 'Thousand Island Dressing','foodcategory_id'=> 9],
            ['name' => 'Turkey Gravy','foodcategory_id'=> 9],
            ['name' => 'Vegetable Dipping Sauce','foodcategory_id'=> 9],
            ['name' => 'Vegetable Medley with Salsa Dip','foodcategory_id'=> 9],
            ['name' => 'Vegetarian Spaghetti Sauce','foodcategory_id'=> 9],
            ['name' => 'Veggie Dip','foodcategory_id'=> 9],
            ['name' => 'White Sauce - Thin','foodcategory_id'=> 9],
            ['name' => 'Zesty Herb Salad Dressing','foodcategory_id'=> 9],



            ['name' => '3-Can Chili','foodcategory_id'=> 10],
            ['name' => '5 A Day Salad','foodcategory_id'=> 10],
            ['name' => 'Apple Coleslaw','foodcategory_id'=> 10],
            ['name' => 'Apple Cranberry Salad Toss','foodcategory_id'=> 10],
            ['name' => 'Apple Salad','foodcategory_id'=> 10],
            ['name' => 'Apple Salad with Sweet & Tangy Yogurt Dressing','foodcategory_id'=> 10],
            ['name' => 'Apple-Sage Wild Rice Stuffing','foodcategory_id'=> 10],
            ['name' => 'Apple-Stuffed Squash','foodcategory_id'=> 10],
            ['name' => 'Applesauce','foodcategory_id'=> 10],
            ['name' => 'Asparagus with Gremolata Sauce','foodcategory_id'=> 10],
            ['name' => 'Au Gratin Potatoes','foodcategory_id'=> 10],
            ['name' => 'Autumn Vegetable Succotash','foodcategory_id'=> 10],
            ['name' => 'Avocado Black Bean Taquitos','foodcategory_id'=> 10],
            ['name' => 'Avocado Pita Pockets','foodcategory_id'=> 10],
            ['name' => 'Avocado Veggie Bake','foodcategory_id'=> 10],
            ['name' => 'Baked Apples and Sweet Potatoes','foodcategory_id'=> 10],
            ['name' => 'Baked Beans','foodcategory_id'=> 10],
            ['name' => 'Baked Cauliflower Tots','foodcategory_id'=> 10],
            ['name' => 'Baked Potatoes Primavera','foodcategory_id'=> 10],
            ['name' => 'Banana Waldorf','foodcategory_id'=> 10],
            ['name' => 'Barley Pilaf','foodcategory_id'=> 10],
            ['name' => 'Basic Steamed Collards','foodcategory_id'=> 10],
            ['name' => 'Beet & White Bean Salad','foodcategory_id'=> 10],
            ['name' => 'Beets, Beans, and Greens','foodcategory_id'=> 10],
            ['name' => 'Bell Pepper and Apple Coleslaw','foodcategory_id'=> 10],
            ['name' => 'Bell Pepper and Potato Salad','foodcategory_id'=> 10],
            ['name' => 'Black Bean and Rice Salad','foodcategory_id'=> 10],
            ['name' => 'Black Bean Quesadillas','foodcategory_id'=> 10],
            ['name' => 'Black Bean Salsa','foodcategory_id'=> 10],
            ['name' => 'Black Bean Soup','foodcategory_id'=> 10],
            ['name' => 'Brazilian Rice','foodcategory_id'=> 10],
            ['name' => 'Bread in a Bag','foodcategory_id'=> 10],
            ['name' => 'Broccoli and Corn Bake','foodcategory_id'=> 10],
            ['name' => 'Broccoli Baked Potatoes','foodcategory_id'=> 10],
            ['name' => 'Broccoli Salad','foodcategory_id'=> 10],
            ['name' => 'Broiled Tomatoes and Cheese','foodcategory_id'=> 10],
            ['name' => 'Brown Rice Pilaf','foodcategory_id'=> 10],
            ['name' => 'Brown Rice Pilaf with Sage, Walnuts, and Dried Fruit','foodcategory_id'=> 10],
            ['name' => 'Brown Rice Tabbouleh','foodcategory_id'=> 10],
            ['name' => 'Brussel Sprouts, Cranberry, and Bulgur Salad','foodcategory_id'=> 10],
            ['name' => 'Brussels Sprouts with Mushroom Sauce','foodcategory_id'=> 10],
            ['name' => 'Bulgur Chickpea Salad','foodcategory_id'=> 10],
            ['name' => 'Bulgur Wheat, Veggie & Chickpea Salad','foodcategory_id'=> 10],
            ['name' => 'Butternut Squash with Black Beans','foodcategory_id'=> 10],
            ['name' => 'Cabbage Salad','foodcategory_id'=> 10],
            ['name' => 'Cabbage Stir-Fry','foodcategory_id'=> 10],
            ['name' => 'Candied Yams','foodcategory_id'=> 10],
            ['name' => 'Caribbean Bean Salad','foodcategory_id'=> 10],
            ['name' => 'Caribbean Pink Beans','foodcategory_id'=> 10],
            ['name' => 'Carrot Raisin Salad','foodcategory_id'=> 10],
            ['name' => 'Carrots with Tomatoes and Macaroni','foodcategory_id'=> 10],
            ['name' => 'Cauliflower Shells with Cheese','foodcategory_id'=> 10],
            ['name' => 'Cheese Stuffed Potatoes','foodcategory_id'=> 10],
            ['name' => 'Cherry, Melon, & Grape Salad','foodcategory_id'=> 10],
            ['name' => 'Chicken Pasta Salad','foodcategory_id'=> 10],
            ['name' => 'Chicken Posole','foodcategory_id'=> 10],
            ['name' => 'Chicken Salad with Ramen Noodles','foodcategory_id'=> 10],
            ['name' => 'Chicken Stew','foodcategory_id'=> 10],
            ['name' => 'Chilled Blueberry Soup','foodcategory_id'=> 10],
            ['name' => 'Citrus Vegetables','foodcategory_id'=> 10],
            ['name' => 'Classic Macaroni and Cheese','foodcategory_id'=> 10],
            ['name' => 'Colorful Quesadillas','foodcategory_id'=> 10],
            ['name' => 'Confetti Grain Salad','foodcategory_id'=> 10],
            ['name' => 'Cooked Beans','foodcategory_id'=> 10],
            ['name' => 'Corn and Bean Medley','foodcategory_id'=> 10],
            ['name' => 'Corn and Cucumber Salad','foodcategory_id'=> 10],
            ['name' => 'Corn and Green Chili Salad','foodcategory_id'=> 10],
            ['name' => 'Corn and Pepper Cups','foodcategory_id'=> 10],
            ['name' => 'Corn Casserole','foodcategory_id'=> 10],
            ['name' => 'Corn Salad with Fresh Basil and Lemon','foodcategory_id'=> 10],
            ['name' => 'Corn Toasties','foodcategory_id'=> 10],
            ['name' => 'Corn, Blueberry, and Wild Rice Salad','foodcategory_id'=> 10],
            ['name' => 'Cornbread Dressing','foodcategory_id'=> 10],
            ['name' => 'Country Style Potato Salad','foodcategory_id'=> 10],
            ['name' => 'Couscous with Peas and Onions','foodcategory_id'=> 10],
            ['name' => 'Cowboy Caviar (Bean Salsa)','foodcategory_id'=> 10],
            ['name' => 'Cranberry Salad','foodcategory_id'=> 10],
            ['name' => 'Cranberry Wojapi','foodcategory_id'=> 10],
            ['name' => 'Creole Beans','foodcategory_id'=> 10],
            ['name' => 'Crispy Oven Baked Fries','foodcategory_id'=> 10],
            ['name' => 'Cuban Beans and Rice','foodcategory_id'=> 10],
            ['name' => 'Cucumber Blueberry Salad','foodcategory_id'=> 10],
            ['name' => 'Cucumber Salad with Tomatoes','foodcategory_id'=> 10],
            ['name' => 'Curried Potatoes','foodcategory_id'=> 10],
            ['name' => 'Curtido Salvadoreño (Cabbage Salad)','foodcategory_id'=> 10],
            ['name' => 'Dave’s Herb-Stuffed Mushrooms','foodcategory_id'=> 10],
            ['name' => 'Delicious Greens','foodcategory_id'=> 10],
            ['name' => 'Delicious Oven French Fries','foodcategory_id'=> 10],
            ['name' => 'Dirty Rice','foodcategory_id'=> 10],
            ['name' => 'Dutch Green Beans','foodcategory_id'=> 10],
            ['name' => 'Easy Baked Acorn Squash','foodcategory_id'=> 10],
            ['name' => 'Easy Oven Packet Caribbean Tilapia with Pears and Carnival Roasted Potatoes','foodcategory_id'=> 10],
            ['name' => 'Eggplant Stir Fry','foodcategory_id'=> 10],
            ['name' => 'Elaine’s Green-Mash Potatoes','foodcategory_id'=> 10],
            ['name' => 'Fiesta Rice Salad','foodcategory_id'=> 10],
            ['name' => 'Fiesta Stuffed Avocado','foodcategory_id'=> 10],
            ['name' => 'Fried Rice with Chicken and Vegetables','foodcategory_id'=> 10],
            ['name' => 'Fruit & Feta Salad','foodcategory_id'=> 10],
            ['name' => 'Fruit Cole Slaw','foodcategory_id'=> 10],
            ['name' => 'Fruit Salad with Yogurt','foodcategory_id'=> 10],
            ['name' => 'Garden Cannellini Bean Salad','foodcategory_id'=> 10],
            ['name' => 'Garden Pasta Salad','foodcategory_id'=> 10],
            ['name' => 'Garlic Bok Choy','foodcategory_id'=> 10],
            ['name' => 'Gingery Quinoa with Green Beans','foodcategory_id'=> 10],
            ['name' => 'Glazed Carrots','foodcategory_id'=> 10],
            ['name' => 'Grandmas Stuffing','foodcategory_id'=> 10],
            ['name' => 'Greek Salad','foodcategory_id'=> 10],
            ['name' => 'Green Bean and Mushroom Medley','foodcategory_id'=> 10],
            ['name' => 'Green Bean and Rice Casserole','foodcategory_id'=> 10],
            ['name' => 'Green Bean Sauté','foodcategory_id'=> 10],
            ['name' => 'Green Beans and New Potatoes','foodcategory_id'=> 10],
            ['name' => 'Green Beans with Tomatoes and Basil','foodcategory_id'=> 10],
            ['name' => 'Grilled Vegetable Packets','foodcategory_id'=> 10],
            ['name' => 'Grilled Vegetables','foodcategory_id'=> 10],
            ['name' => 'Hearty Mashed Potatoes','foodcategory_id'=> 10],
            ['name' => 'Heavenly Deviled Eggs','foodcategory_id'=> 10],
            ['name' => 'Herb Spinach Bake','foodcategory_id'=> 10],
            ['name' => 'Herbed Vegetables','foodcategory_id'=> 10],
            ['name' => 'Homemade Cranberry Sauce','foodcategory_id'=> 10],
            ['name' => 'Homemade Mashed Potatoes','foodcategory_id'=> 10],
            ['name' => 'Honey Baked Lentils','foodcategory_id'=> 10],
            ['name' => 'Honeydew Summer Salad Wedges','foodcategory_id'=> 10],
            ['name' => 'Italian Pasta Salad','foodcategory_id'=> 10],
            ['name' => 'Italian Style Vegetables','foodcategory_id'=> 10],
            ['name' => 'Italian Vegetables','foodcategory_id'=> 10],
            ['name' => 'Julia’s Sautéed & Steamed Collards','foodcategory_id'=> 10],
            ['name' => 'Kale and Cranberry Stir-Fry','foodcategory_id'=> 10],
            ['name' => 'Kale Chips','foodcategory_id'=> 10],
            ['name' => 'Kale Salad with Yogurt Dressing','foodcategory_id'=> 10],
            ['name' => 'Leafy Tofu','foodcategory_id'=> 10],
            ['name' => 'Lemon Corn Cake','foodcategory_id'=> 10],
            ['name' => 'Lemon Dill Brussels Sprouts','foodcategory_id'=> 10],
            ['name' => 'Lemon Potatoes','foodcategory_id'=> 10],
            ['name' => 'Lemon Spinach','foodcategory_id'=> 10],
            ['name' => 'Lite Fried Okra','foodcategory_id'=> 10],
            ['name' => 'Louisiana Green Beans','foodcategory_id'=> 10],
            ['name' => 'Mac and Beans Medley','foodcategory_id'=> 10],
            ['name' => 'Mango Berry Rotini Salad','foodcategory_id'=> 10],
            ['name' => 'Manhattan Clam Chowder','foodcategory_id'=> 10],
            ['name' => 'Maple Sweet Potatoes','foodcategory_id'=> 10],
            ['name' => 'Marinated Three-Bean Salad','foodcategory_id'=> 10],
            ['name' => 'Mashed Parsnips and Potatoes','foodcategory_id'=> 10],
            ['name' => 'Mashed Sweet Potatoes','foodcategory_id'=> 10],
            ['name' => 'Mashed Taters','foodcategory_id'=> 10],
            ['name' => 'Masoor Dal (Red Lentils with Onion)','foodcategory_id'=> 10],
            ['name' => 'Mediterranean Chicken and White Bean Salad','foodcategory_id'=> 10],
            ['name' => 'Mediterranean Roasted Eggplant with Tomato Sauce','foodcategory_id'=> 10],
            ['name' => 'Melissa’s Slow Cooker Stuffing','foodcategory_id'=> 10],
            ['name' => 'Microwave Baked Potato','foodcategory_id'=> 10],
            ['name' => 'Microwave Cauliflower and Peas in Cream Sauce','foodcategory_id'=> 10],
            ['name' => 'Mini Caprese Bites','foodcategory_id'=> 10],
            ['name' => 'Mozz Totz','foodcategory_id'=> 10],
            ['name' => 'New Orleans Red Beans','foodcategory_id'=> 10],
            ['name' => 'Okra and Greens','foodcategory_id'=> 10],
            ['name' => 'Old Fashioned Dressing','foodcategory_id'=> 10],
            ['name' => 'Orange Honeyed Acorn Squash','foodcategory_id'=> 10],
            ['name' => 'Oven Baked Sweet Potato Fries','foodcategory_id'=> 10],
            ['name' => 'Oven-Baked Potato Pancakes','foodcategory_id'=> 10],
            ['name' => 'Oven-Fried Yucca','foodcategory_id'=> 10],
            ['name' => 'Oven-Roasted Vegetables','foodcategory_id'=> 10],
            ['name' => 'Panned Cabbage','foodcategory_id'=> 10],
            ['name' => 'Pasta Frittata with Peas','foodcategory_id'=> 10],
            ['name' => 'Pasta Primavera Salad','foodcategory_id'=> 10],
            ['name' => 'Pasta Salad','foodcategory_id'=> 10],
            ['name' => 'Polenta with Pepper and Cheese','foodcategory_id'=> 10],
            ['name' => 'Potato Cakes','foodcategory_id'=> 10],
            ['name' => 'Potato Salad','foodcategory_id'=> 10],
            ['name' => 'Potato Spinach Casserole','foodcategory_id'=> 10],
            ['name' => 'Pumpkin Mac & Cheese for One','foodcategory_id'=> 10],
            ['name' => 'Quick and Easy Baked Potato Salad','foodcategory_id'=> 10],
            ['name' => 'Quick and Easy Potato Casserole','foodcategory_id'=> 10],
            ['name' => 'Quick and Healthy Black-Eyed Peas','foodcategory_id'=> 10],
            ['name' => 'Quick Black Bean Salad','foodcategory_id'=> 10],
            ['name' => 'Quinoa and Black Bean Salad','foodcategory_id'=> 10],
            ['name' => 'Rainbow Veggie Salad','foodcategory_id'=> 10],
            ['name' => 'Ratatouille','foodcategory_id'=> 10],
            ['name' => 'Ratatouille','foodcategory_id'=> 10],
            ['name' => 'Red Beans and Rice','foodcategory_id'=> 10],
            ['name' => 'Red Lentil Latkes','foodcategory_id'=> 10],
            ['name' => 'Red Potato and Cabbage (Colcannon)','foodcategory_id'=> 10],
            ['name' => 'Red Potato Salad','foodcategory_id'=> 10],
            ['name' => 'Refried Beans','foodcategory_id'=> 10],
            ['name' => 'Roasted Bell Peppers','foodcategory_id'=> 10],
            ['name' => 'Roasted Brussels Sprouts','foodcategory_id'=> 10],
            ['name' => 'Roasted Cauliflower','foodcategory_id'=> 10],
            ['name' => 'Roasted Cauliflower Steaks','foodcategory_id'=> 10],
            ['name' => 'Roasted Herb Potatoes','foodcategory_id'=> 10],
            ['name' => 'Roasted Potatoes','foodcategory_id'=> 10],
            ['name' => 'Roasted Root Vegetables','foodcategory_id'=> 10],
            ['name' => 'Roasted Tomatoes with Herbs','foodcategory_id'=> 10],
            ['name' => 'Salad with Pineapple, Nuts, and Raisins','foodcategory_id'=> 10],
            ['name' => 'Salmon Burgers and Sweet Potato Oven Fries','foodcategory_id'=> 10],
            ['name' => 'Salsa Pinto Beans','foodcategory_id'=> 10],
            ['name' => 'Sarah’s Green Bean Casserole','foodcategory_id'=> 10],
            ['name' => 'Sautéed Beet Greens','foodcategory_id'=> 10],
            ['name' => 'Sautéed Cabbage and Onion','foodcategory_id'=> 10],
            ['name' => 'Sautéed Cauliflower Rice','foodcategory_id'=> 10],
            ['name' => 'Scallion Rice','foodcategory_id'=> 10],
            ['name' => 'Scalloped Potatoes','foodcategory_id'=> 10],
            ['name' => 'Scalloped Potatoes II','foodcategory_id'=> 10],
            ['name' => 'Seared Greens','foodcategory_id'=> 10],
            ['name' => 'Seasoned Roasted Vegetables','foodcategory_id'=> 10],
            ['name' => 'Sesame Turnips and Carrots','foodcategory_id'=> 10],
            ['name' => 'Simmered Beans','foodcategory_id'=> 10],
            ['name' => 'Slow Cooker Beans','foodcategory_id'=> 10],
            ['name' => 'Smoked Ham Hocks with Lima Beans','foodcategory_id'=> 10],
            ['name' => 'Smothered Greens','foodcategory_id'=> 10],
            ['name' => 'Snappy Cole Slaw','foodcategory_id'=> 10],
            ['name' => 'Snappy Rice Dish','foodcategory_id'=> 10],
            ['name' => 'South of the Border Salad','foodcategory_id'=> 10],
            ['name' => 'Southwestern Pepper Cups','foodcategory_id'=> 10],
            ['name' => 'Spaghetti and Spinach Pesto','foodcategory_id'=> 10],
            ['name' => 'Spaghetti Squash with Tomatoes, Basil, and Parmesan','foodcategory_id'=> 10],
            ['name' => 'Spanish Rice','foodcategory_id'=> 10],
            ['name' => 'Spicy Baked Squash','foodcategory_id'=> 10],
            ['name' => 'Spicy Carrots and Squash','foodcategory_id'=> 10],
            ['name' => 'Spicy Chicken and Potato Soup','foodcategory_id'=> 10],
            ['name' => 'Spicy Cucumber & Orange Salad','foodcategory_id'=> 10],
            ['name' => 'Spicy Okra','foodcategory_id'=> 10],
            ['name' => 'Spinach Black Bean Salad','foodcategory_id'=> 10],
            ['name' => 'Spinach Rice Salad','foodcategory_id'=> 10],
            ['name' => 'Spinach Stuffed Potatoes','foodcategory_id'=> 10],
            ['name' => 'Spinach, Tomatoes, and Corn','foodcategory_id'=> 10],
            ['name' => 'Spring Vegetable Sauté','foodcategory_id'=> 10],
            ['name' => 'Squash Squares','foodcategory_id'=> 10],
            ['name' => 'Squash-Apple Casserole','foodcategory_id'=> 10],
            ['name' => 'Stewed Cauliflower, Tomatoes, and Onions','foodcategory_id'=> 10],
            ['name' => 'Stove Top Casserole','foodcategory_id'=> 10],
            ['name' => 'Stuffed Tomatoes','foodcategory_id'=> 10],
            ['name' => 'Summer Italian Vegetables','foodcategory_id'=> 10],
            ['name' => 'Summer Salad','foodcategory_id'=> 10],
            ['name' => 'Summer Squash Medley','foodcategory_id'=> 10],
            ['name' => 'Summer Squash Stir Fry','foodcategory_id'=> 10],
            ['name' => 'Summer Squash, Italian Style','foodcategory_id'=> 10],
            ['name' => 'Sunshine Rice','foodcategory_id'=> 10],
            ['name' => 'Sunshine Salad','foodcategory_id'=> 10],
            ['name' => 'Sweet Acorn Squash','foodcategory_id'=> 10],
            ['name' => 'Sweet and Sour Cabbage','foodcategory_id'=> 10],
            ['name' => 'Sweet and Sour Vegetables','foodcategory_id'=> 10],
            ['name' => 'Sweet Potato and Apple Bake','foodcategory_id'=> 10],
            ['name' => 'Sweet Potato Casserole','foodcategory_id'=> 10],
            ['name' => 'Sweet Potato Casserole','foodcategory_id'=> 10],
            ['name' => 'Sweet Potato Harvest Salad','foodcategory_id'=> 10],
            ['name' => 'Sweet Potato Pancakes','foodcategory_id'=> 10],
            ['name' => 'Sweet Potato Patties','foodcategory_id'=> 10],
            ['name' => 'Taco Flavored Potatoes','foodcategory_id'=> 10],
            ['name' => 'Tangy Crisp Vegetable and Pasta Salad','foodcategory_id'=> 10],
            ['name' => 'Tangy Jicama Slaw','foodcategory_id'=> 10],
            ['name' => 'The Perfect "Pear" and Brussels Sprout Salad','foodcategory_id'=> 10],
            ['name' => 'Three Bean Salad','foodcategory_id'=> 10],
            ['name' => 'Tomato and Cucumber Salad','foodcategory_id'=> 10],
            ['name' => 'Tomato Basil and Bean Pasta Salad','foodcategory_id'=> 10],
            ['name' => 'Tropical Morning Treat','foodcategory_id'=> 10],
            ['name' => 'Tuna Veggie Antipasto','foodcategory_id'=> 10],
            ['name' => 'Turkey Potato Salad','foodcategory_id'=> 10],
            ['name' => 'Turnip Pancakes','foodcategory_id'=> 10],
            ['name' => 'Vegetable Fried Rice','foodcategory_id'=> 10],
            ['name' => 'Vegetable Rice with Tomatoes','foodcategory_id'=> 10],
            ['name' => 'Vegetable Salad','foodcategory_id'=> 10],
            ['name' => 'Vegetarian Collard Greens','foodcategory_id'=> 10],
            ['name' => 'Vegetarian Stuffed Peppers','foodcategory_id'=> 10],
            ['name' => 'Veggie Stir-Fry with Turkey','foodcategory_id'=> 10],
            ['name' => 'Waldorf Salad','foodcategory_id'=> 10],
            ['name' => 'Whole Wheat Garlic Bread Sticks','foodcategory_id'=> 10],
            ['name' => 'Wonderful Stuffed Potatoes','foodcategory_id'=> 10],
            ['name' => 'Zesty Citrus Coleslaw','foodcategory_id'=> 10],
            ['name' => 'Zesty Orange Carrots','foodcategory_id'=> 10],
            ['name' => 'Zesty Pasta Primavera Salad','foodcategory_id'=> 10],
            ['name' => 'Zesty Skillet Zucchini','foodcategory_id'=> 10],
            ['name' => 'Zucchini And Tomatoes','foodcategory_id'=> 10],
            ['name' => 'Zucchini Au Gratin','foodcategory_id'=> 10],
            ['name' => 'Zucchini Coleslaw','foodcategory_id'=> 10],
            ['name' => 'Zucchini Pancakes','foodcategory_id'=> 10],
            ['name' => 'Zucchini Recipe','foodcategory_id'=> 10],
            ['name' => 'Zucchini Stir Fry','foodcategory_id'=> 10],



            ['name' => 'Ambrosia','foodcategory_id'=> 11],
            ['name' => 'Any Days a Picnic Chicken Salad','foodcategory_id'=> 11],
            ['name' => 'Apple Sandwiches','foodcategory_id'=> 11],
            ['name' => 'Apple Tuna Sandwiches','foodcategory_id'=> 11],
            ['name' => 'Apple Wedges with Pumpkin Almond Butter','foodcategory_id'=> 11],
            ['name' => 'Applesauce','foodcategory_id'=> 11],
            ['name' => 'Avocado and Corn Salsa','foodcategory_id'=> 11],
            ['name' => 'Avocado Black Bean Taquitos','foodcategory_id'=> 11],
            ['name' => 'Avocado Pita Pockets','foodcategory_id'=> 11],
            ['name' => 'Avocado Veggie Bake','foodcategory_id'=> 11],
            ['name' => 'Baked Bananas','foodcategory_id'=> 11],
            ['name' => 'Baked Cauliflower Tots','foodcategory_id'=> 11],
            ['name' => 'Baked Tortilla Chips','foodcategory_id'=> 11],
            ['name' => 'Banana Cocoa Yogurt Pops','foodcategory_id'=> 11],
            ['name' => 'Banana Oatmeal Raisin Cookies','foodcategory_id'=> 11],
            ['name' => 'Batido (Smoothie)','foodcategory_id'=> 11],
            ['name' => 'BBQ Chicken Pizza','foodcategory_id'=> 11],
            ['name' => 'Berries with Banana Cream','foodcategory_id'=> 11],
            ['name' => 'Black Bean and Sweet Potato Quesadillas','foodcategory_id'=> 11],
            ['name' => 'Black Bean Burrito','foodcategory_id'=> 11],
            ['name' => 'Black Bean Salsa','foodcategory_id'=> 11],
            ['name' => 'Blueberry Coffee Cake','foodcategory_id'=> 11],
            ['name' => 'Breakfast Parfait','foodcategory_id'=> 11],
            ['name' => 'Bugs on a Log','foodcategory_id'=> 11],
            ['name' => 'Bulgur Chickpea Salad','foodcategory_id'=> 11],
            ['name' => 'Butterfly Bite','foodcategory_id'=> 11],
            ['name' => 'Buttermilk Scones','foodcategory_id'=> 11],
            ['name' => 'Celery with Apricot Blue Cheese Spread','foodcategory_id'=> 11],
            ['name' => 'Cherry Puff Pancake','foodcategory_id'=> 11],
            ['name' => 'Cherry, Melon, & Grape Salad','foodcategory_id'=> 11],
            ['name' => 'Chickpea Dip','foodcategory_id'=> 11],
            ['name' => 'Chili Popcorn','foodcategory_id'=> 11],
            ['name' => 'Chocolate Chip Yogurt Cookies','foodcategory_id'=> 11],
            ['name' => 'Chunky Garbanzo Bean Dip','foodcategory_id'=> 11],
            ['name' => 'Cinnamon-Raisin Breakfast Mix','foodcategory_id'=> 11],
            ['name' => 'Cookie Cutter Appetizers','foodcategory_id'=> 11],
            ['name' => 'Corn Toasties','foodcategory_id'=> 11],
            ['name' => 'Cranberry Pumpkin Muffins','foodcategory_id'=> 11],
            ['name' => 'Crispy Taquitos','foodcategory_id'=> 11],
            ['name' => 'Crunchy Berry Parfait','foodcategory_id'=> 11],
            ['name' => 'Crunchy Vegetable Wraps','foodcategory_id'=> 11],
            ['name' => 'Cucumber, Yogurt and Herb Dip','foodcategory_id'=> 11],
            ['name' => 'Curry Vegetable Dip','foodcategory_id'=> 11],
            ['name' => 'Delicious Oven French Fries','foodcategory_id'=> 11],
            ['name' => 'Dried Bananas','foodcategory_id'=> 11],
            ['name' => 'Dutch Apple Yogurt Dessert','foodcategory_id'=> 11],
            ['name' => 'Nido del águila','foodcategory_id'=> 11],
            ['name' => 'Easiest Banana Ice Cream','foodcategory_id'=> 11],
            ['name' => 'English Muffin Veggie Pizza','foodcategory_id'=> 11],
            ['name' => 'Fabulous Fig Bars','foodcategory_id'=> 11],
            ['name' => 'Fiesta Hummus','foodcategory_id'=> 11],
            ['name' => 'Fiesta Mix','foodcategory_id'=> 11],
            ['name' => 'Fiesta Stuffed Avocado','foodcategory_id'=> 11],
            ['name' => 'Food Group Funny Face','foodcategory_id'=> 11],
            ['name' => 'Fresh Fruit with Cinnamon Yogurt Dip','foodcategory_id'=> 11],
            ['name' => 'Frozen Banana Pops','foodcategory_id'=> 11],
            ['name' => 'Frozen Fruit Cups','foodcategory_id'=> 11],
            ['name' => 'Frozen Fruit Pops','foodcategory_id'=> 11],
            ['name' => 'Fruit and Peanut Butter Dip','foodcategory_id'=> 11],
            ['name' => 'Fruit and Yogurt Breakfast Shake','foodcategory_id'=> 11],
            ['name' => 'Fruit Compote','foodcategory_id'=> 11],
            ['name' => 'Fruit Dip','foodcategory_id'=> 11],
            ['name' => 'Fruit Dippers','foodcategory_id'=> 11],
            ['name' => 'Fruit Juice Slush','foodcategory_id'=> 11],
            ['name' => 'Fruit Kabob','foodcategory_id'=> 11],
            ['name' => 'Fruit Kabobs with Yogurt Dip','foodcategory_id'=> 11],
            ['name' => 'Fruit Milk Shakes','foodcategory_id'=> 11],
            ['name' => 'Fruit Pizza To Go','foodcategory_id'=> 11],
            ['name' => 'Fruit Salad','foodcategory_id'=> 11],
            ['name' => 'Fruit Salsa','foodcategory_id'=> 11],
            ['name' => 'Fruit Slush','foodcategory_id'=> 11],
            ['name' => 'Fruit Snake','foodcategory_id'=> 11],
            ['name' => 'Fruit Yogurt Parfait','foodcategory_id'=> 11],
            ['name' => 'Fruit Yogurt Pops','foodcategory_id'=> 11],
            ['name' => 'Fruity Thai Pita Pockets','foodcategory_id'=> 11],
            ['name' => 'Granola Bars','foodcategory_id'=> 11],
            ['name' => 'Grape Salsa','foodcategory_id'=> 11],
            ['name' => 'Grilled Fruit','foodcategory_id'=> 11],
            ['name' => 'Grilled Steak and Peppers Salad with Pears','foodcategory_id'=> 11],
            ['name' => 'Grilled Vegetables','foodcategory_id'=> 11],
            ['name' => 'Hiding Rabbits','foodcategory_id'=> 11],
            ['name' => 'Honey Milk Balls','foodcategory_id'=> 11],
            ['name' => 'Honeydew Summer Salad Wedges','foodcategory_id'=> 11],
            ['name' => 'Hummus','foodcategory_id'=> 11],
            ['name' => 'Kale Chips','foodcategory_id'=> 11],
            ['name' => 'Layered Black Bean Dip','foodcategory_id'=> 11],
            ['name' => 'Leaf Finger Salad','foodcategory_id'=> 11],
            ['name' => 'Lentil Tacos','foodcategory_id'=> 11],
            ['name' => 'Magical Fruit Salad','foodcategory_id'=> 11],
            ['name' => 'Mango Shake','foodcategory_id'=> 11],
            ['name' => 'Melon and Mint','foodcategory_id'=> 11],
            ['name' => 'Microwave Baked Apple','foodcategory_id'=> 11],
            ['name' => 'Migas "Crumbs"','foodcategory_id'=> 11],
            ['name' => 'Mini Caprese Bites','foodcategory_id'=> 11],
            ['name' => 'Mousse a la Banana','foodcategory_id'=> 11],
            ['name' => 'Mozz Totz','foodcategory_id'=> 11],
            ['name' => 'No Bake Breakfast Cookies','foodcategory_id'=> 11],
            ['name' => 'Oat Snack Cakes','foodcategory_id'=> 11],
            ['name' => 'Oven-Fried Yucca','foodcategory_id'=> 11],
            ['name' => 'Pea Guacamole','foodcategory_id'=> 11],
            ['name' => 'Peach Cooler','foodcategory_id'=> 11],
            ['name' => 'Peachy Peanut Butter Pita Pockets','foodcategory_id'=> 11],
            ['name' => 'Peachy Pops','foodcategory_id'=> 11],
            ['name' => 'Peanut Butter n Fruit-wich','foodcategory_id'=> 11],
            ['name' => 'Peanut Butter Banana Breakfast Shake','foodcategory_id'=> 11],
            ['name' => 'Peanut Butter Cereal Bars','foodcategory_id'=> 11],
            ['name' => 'Pear Kabobs with Strawberry Dipping Sauce','foodcategory_id'=> 11],
            ['name' => 'Pear Party Salsa','foodcategory_id'=> 11],
            ['name' => 'Pear PB&J Bouquet','foodcategory_id'=> 11],
            ['name' => 'Pear Rabbit','foodcategory_id'=> 11],
            ['name' => 'Pears in a Pod','foodcategory_id'=> 11],
            ['name' => 'Peter Pumpkin Squares','foodcategory_id'=> 11],
            ['name' => 'Pocket Fruit Pies','foodcategory_id'=> 11],
            ['name' => 'Popcorn Treats','foodcategory_id'=> 11],
            ['name' => 'Potato Cakes','foodcategory_id'=> 11],
            ['name' => 'Potato Skins with Buffalo Chicken','foodcategory_id'=> 11],
            ['name' => 'Pretzel Shapes','foodcategory_id'=> 11],
            ['name' => 'Pumpkin Bread','foodcategory_id'=> 11],
            ['name' => 'Pumpkin Cookies','foodcategory_id'=> 11],
            ['name' => 'Pumpkin Pudding','foodcategory_id'=> 11],
            ['name' => 'Quick and Easy Bean Dip','foodcategory_id'=> 11],
            ['name' => 'Rise and Shine Cobbler','foodcategory_id'=> 11],
            ['name' => 'Roasted Pumpkin Seed Snack Mix','foodcategory_id'=> 11],
            ['name' => 'Salmon Spread','foodcategory_id'=> 11],
            ['name' => 'Simple Fish Tacos','foodcategory_id'=> 11],
            ['name' => 'Sloppy Garden Joes','foodcategory_id'=> 11],
            ['name' => 'Soft Pretzels','foodcategory_id'=> 11],
            ['name' => 'Speedy Burritos','foodcategory_id'=> 11],
            ['name' => 'Spicy Fruit Cup','foodcategory_id'=> 11],
            ['name' => 'Spinach Black Bean Salad','foodcategory_id'=> 11],
            ['name' => 'Springtime Cereal','foodcategory_id'=> 11],
            ['name' => 'Strawberry and Banana Fruit Smoothie','foodcategory_id'=> 11],
            ['name' => 'Strawberry Kiwi Yogurt Pops','foodcategory_id'=> 11],
            ['name' => 'Strawberry Mango Feta Toast Points','foodcategory_id'=> 11],
            ['name' => 'Strawberry SMores','foodcategory_id'=> 11],
            ['name' => 'Strawberry Yogurt Pops','foodcategory_id'=> 11],
            ['name' => 'Summer Breeze Smoothie','foodcategory_id'=> 11],
            ['name' => 'Sweet and Juicy Raisin Tapenade','foodcategory_id'=> 11],
            ['name' => 'Sweet and Savory Peanut Butter Dip','foodcategory_id'=> 11],
            ['name' => 'Sweet Potato Patties','foodcategory_id'=> 11],
            ['name' => 'Terrific Bean Taco','foodcategory_id'=> 11],
            ['name' => 'Tic Tac Toe Veggie Pizza','foodcategory_id'=> 11],
            ['name' => 'Tofu Salad','foodcategory_id'=> 11],
            ['name' => 'Tomato Basil Bruschetta','foodcategory_id'=> 11],
            ['name' => 'Tortilla Chips and Bean Dip','foodcategory_id'=> 11],
            ['name' => 'Tostadas Delgadas','foodcategory_id'=> 11],
            ['name' => 'Trail Mix Bars','foodcategory_id'=> 11],
            ['name' => 'Trail Treat','foodcategory_id'=> 11],
            ['name' => 'Tropical Morning Treat','foodcategory_id'=> 11],
            ['name' => 'Tropical Yogurt Pops','foodcategory_id'=> 11],
            ['name' => 'Tuna Melt Burger','foodcategory_id'=> 11],
            ['name' => 'Tuna Quesadillas','foodcategory_id'=> 11],
            ['name' => 'Tuna Salad with Grapes','foodcategory_id'=> 11],
            ['name' => 'Tuna Veggie Antipasto','foodcategory_id'=> 11],
            ['name' => 'Turkey Pinwheel Appetizers','foodcategory_id'=> 11],
            ['name' => 'Turnip Pancakes','foodcategory_id'=> 11],
            ['name' => 'Turtle Apple','foodcategory_id'=> 11],
            ['name' => 'Vegetable Medley with Salsa Dip','foodcategory_id'=> 11],
            ['name' => 'Vegetable Pinwheels','foodcategory_id'=> 11],
            ['name' => 'Vegetable Snake','foodcategory_id'=> 11],
            ['name' => 'Veggie Quesadillas','foodcategory_id'=> 11],
            ['name' => 'Veggie Stuffed Pita','foodcategory_id'=> 11],
            ['name' => 'Very Berry Muesli','foodcategory_id'=> 11],
            ['name' => 'Waldorf Salad','foodcategory_id'=> 11],
            ['name' => 'White Bean Bruschetta','foodcategory_id'=> 11],
            ['name' => 'Wild Rice Muffins','foodcategory_id'=> 11],
            ['name' => 'Yogurt Berry Parfait','foodcategory_id'=> 11],
            ['name' => 'Yogurt Pops','foodcategory_id'=> 11],
            ['name' => 'Yogurt Popsicles','foodcategory_id'=> 11],
            ['name' => 'Yogurt Smoothie in a Bag','foodcategory_id'=> 11],
            ['name' => 'Zucchini Pancakes','foodcategory_id'=> 11],


            ['name' => '3-Can Chili','foodcategory_id'=> 12],
            ['name' => 'Apple Carrot Soup','foodcategory_id'=> 12],
            ['name' => 'Apple Corn Chili','foodcategory_id'=> 12],
            ['name' => 'Barley Jambalaya','foodcategory_id'=> 12],
            ['name' => 'Beef & Vegetable Soup','foodcategory_id'=> 12],
            ['name' => 'Beef and Vegetable Soup','foodcategory_id'=> 12],
            ['name' => 'Beef Pozole Soup','foodcategory_id'=> 12],
            ['name' => 'Black Bean Soup','foodcategory_id'=> 12],
            ['name' => 'Black Bean Soup','foodcategory_id'=> 12],
            ['name' => 'Black-Eyed Pea and Collard Greens Soup','foodcategory_id'=> 12],
            ['name' => 'Brilliant Chili Topped with Walnuts','foodcategory_id'=> 12],
            ['name' => 'Broccoli Potato Soup','foodcategory_id'=> 12],
            ['name' => 'Brunswick Stew','foodcategory_id'=> 12],
            ['name' => 'Catfish Stew and Rice','foodcategory_id'=> 12],
            ['name' => 'Cheese and Corn Chowder','foodcategory_id'=> 12],
            ['name' => 'Chicken & Rice Soup','foodcategory_id'=> 12],
            ['name' => 'Chicken and Dumpling Soup','foodcategory_id'=> 12],
            ['name' => 'Chicken Noodle Soup','foodcategory_id'=> 12],
            ['name' => 'Chicken Noodle Soup','foodcategory_id'=> 12],
            ['name' => 'Chicken Posole','foodcategory_id'=> 12],
            ['name' => 'Chicken Pozole Soup','foodcategory_id'=> 12],
            ['name' => 'Chicken Soup with Chiles','foodcategory_id'=> 12],
            ['name' => 'Chicken Stew','foodcategory_id'=> 12],
            ['name' => 'Chicken Vegetable Soup with Kale','foodcategory_id'=> 12],
            ['name' => 'Chilled Blueberry Soup','foodcategory_id'=> 12],
            ['name' => 'Chilled Cantaloupe Soup','foodcategory_id'=> 12],
            ['name' => 'Corn Soup','foodcategory_id'=> 12],
            ['name' => 'Cream of Broccoli Soup','foodcategory_id'=> 12],
            ['name' => 'Cream of Broccoli Soup II','foodcategory_id'=> 12],
            ['name' => 'Crock Pot Vegetable Lentil Stew','foodcategory_id'=> 12],
            ['name' => 'Curried Squash Stew','foodcategory_id'=> 12],
            ['name' => 'Delicious Lentil Stew','foodcategory_id'=> 12],
            ['name' => 'Easy and Healthy Black Bean Soup','foodcategory_id'=> 12],
            ['name' => 'Farmers Market Gazpacho','foodcategory_id'=> 12],
            ['name' => 'Garden Barley Soup','foodcategory_id'=> 12],
            ['name' => 'Garden Vegetable Soup','foodcategory_id'=> 12],
            ['name' => 'Gazpacho','foodcategory_id'=> 12],
            ['name' => 'Gazpacho Soup','foodcategory_id'=> 12],
            ['name' => 'Golden Split Pea Soup','foodcategory_id'=> 12],
            ['name' => 'Great Northern Bean Soup','foodcategory_id'=> 12],
            ['name' => 'Ground Beef Stew','foodcategory_id'=> 12],
            ['name' => 'Hearty Beef Soup','foodcategory_id'=> 12],
            ['name' => 'Hearty Mexican Soup','foodcategory_id'=> 12],
            ['name' => 'Hearty Vegetable Beef Soup','foodcategory_id'=> 12],
            ['name' => 'Italian Bean Soup','foodcategory_id'=> 12],
            ['name' => 'Kibbeh Khamoustah','foodcategory_id'=> 12],
            ['name' => 'Lentil Barley Soup','foodcategory_id'=> 12],
            ['name' => 'Lentil Chili','foodcategory_id'=> 12],
            ['name' => 'Lentil Minestrone','foodcategory_id'=> 12],
            ['name' => 'Lentil Soup','foodcategory_id'=> 12],
            ['name' => 'Lentil Stew','foodcategory_id'=> 12],
            ['name' => 'Lentil Vegetable Soup','foodcategory_id'=> 12],
            ['name' => 'Macaroni Chick-Pea Soup','foodcategory_id'=> 12],
            ['name' => 'Mango Cucumber Soup','foodcategory_id'=> 12],
            ['name' => 'Manhattan Clam Chowder','foodcategory_id'=> 12],
            ['name' => 'Meatball Soup','foodcategory_id'=> 12],
            ['name' => 'Microwave Potato Corn Chowder','foodcategory_id'=> 12],
            ['name' => 'Minestrone Soup','foodcategory_id'=> 12],
            ['name' => 'Mushroom Barley Soup','foodcategory_id'=> 12],
            ['name' => 'Parsnip Soup','foodcategory_id'=> 12],
            ['name' => 'Peanutty Stew','foodcategory_id'=> 12],
            ['name' => 'Potato Soup','foodcategory_id'=> 12],
            ['name' => 'Potato Soup','foodcategory_id'=> 12],
            ['name' => 'Pumpkin and Bean Soup','foodcategory_id'=> 12],
            ['name' => 'Pumpkin Chili','foodcategory_id'=> 12],
            ['name' => 'Pumpkin Soup','foodcategory_id'=> 12],
            ['name' => 'Pumpkin Soup','foodcategory_id'=> 12],
            ['name' => 'Quick Chicken & Vegetable Soup','foodcategory_id'=> 12],
            ['name' => 'Quick Chili','foodcategory_id'=> 12],
            ['name' => 'Red Chile Stew','foodcategory_id'=> 12],
            ['name' => 'Sarah’s Spicy Curry Turkey Soup','foodcategory_id'=> 12],
            ['name' => 'Shorba (Lamb and Peanut Soup)','foodcategory_id'=> 12],
            ['name' => 'Slow Cooker Beef Stew','foodcategory_id'=> 12],
            ['name' => 'Slow Cooker Hamburger Stew','foodcategory_id'=> 12],
            ['name' => 'Slow Cooker Lentil Soup','foodcategory_id'=> 12],
            ['name' => 'Slow Cooker Pork Stew over Brown Rice','foodcategory_id'=> 12],
            ['name' => 'Smoked Ham Hocks with Lima Beans','foodcategory_id'=> 12],
            ['name' => 'Spicy Chicken and Potato Soup','foodcategory_id'=> 12],
            ['name' => 'Split Pea Soup','foodcategory_id'=> 12],
            ['name' => 'Split Pea Soup','foodcategory_id'=> 12],
            ['name' => 'Spring Vegetable Soup','foodcategory_id'=> 12],
            ['name' => 'Squash Soup','foodcategory_id'=> 12],
            ['name' => 'Taco Soup','foodcategory_id'=> 12],
            ['name' => 'Tasty Low-Fat Cream Soup','foodcategory_id'=> 12],
            ['name' => 'Ten Minute Corn Chowder','foodcategory_id'=> 12],
            ['name' => 'The Bosnian Pot','foodcategory_id'=> 12],
            ['name' => 'Three Sisters Soup','foodcategory_id'=> 12],
            ['name' => 'Tofu, Tomato, and Spinach Soup','foodcategory_id'=> 12],
            ['name' => 'Tomato Basil Soup','foodcategory_id'=> 12],
            ['name' => 'Tortellini Soup','foodcategory_id'=> 12],
            ['name' => 'Turkey Stew','foodcategory_id'=> 12],
            ['name' => 'Two Bean Chili','foodcategory_id'=> 12],
            ['name' => 'Vegetable Cheese Soup','foodcategory_id'=> 12],
            ['name' => 'Vegetable Chili','foodcategory_id'=> 12],
            ['name' => 'Vegetable Soup with Chicken','foodcategory_id'=> 12],
            ['name' => 'Vegetable Stew','foodcategory_id'=> 12],
            ['name' => 'Vegetarian Chili','foodcategory_id'=> 12],
            ['name' => 'Vegetarian Matzo Ball Soup','foodcategory_id'=> 12],
            ['name' => 'Walleye Chowder','foodcategory_id'=> 12],
            ['name' => 'Watermelon Gazpacho','foodcategory_id'=> 12],
            ['name' => 'Wheat Berry Chili','foodcategory_id'=> 12],
            ['name' => 'White Chicken Chili','foodcategory_id'=> 12],
            ['name' => 'White Chili','foodcategory_id'=> 12],

]);




}
}
