<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insert sample data into foods table
        DB::table('foods')->insert([
        ['name' => 'Ambrosia','foodcategory_id'=> 1],
        ['name' => 'Avocado Black Bean Taquitos','foodcategory_id'=> 1],
        ['name' => 'Avocado Pita Pockets','foodcategory_id'=> 1],
        ['name' => 'Avocado Veggie Bake','foodcategory_id'=> 1],
        ['name' => 'Baked Cauliflower Tots','foodcategory_id'=> 1],
        ['name' => 'Baked Chicken Nuggets','foodcategory_id'=> 1],
        ['name' => 'Baked Tortilla Chips','foodcategory_id'=> 1],
        ['name' => 'Beet & White Bean Salad','foodcategory_id'=> 1],
        ['name' => 'Bell Pepper Nachos','foodcategory_id'=> 1],
        ['name' => 'Black Bean Salsa','foodcategory_id'=> 1],
        ['name' => 'Black Bean Soup','foodcategory_id'=> 1],
        ['name' => 'Broiled Tomatoes and Cheese','foodcategory_id'=> 1],
        ['name' => 'Celery with Apricot Blue Cheese Spread','foodcategory_id'=> 1],
        ['name' => 'Cherry, Melon, & Grape Salad','foodcategory_id'=> 1],
        ['name' => 'Chickpea Dip','foodcategory_id'=> 1],
        ['name' => 'Chili Bean Dip','foodcategory_id'=> 1],
        ['name' => 'Chilled Cantaloupe Soup','foodcategory_id'=> 1],
        ['name' => 'Chunky Garbanzo Bean Dip','foodcategory_id'=> 1],
        ['name' => 'Cookie Cutter Appetizers','foodcategory_id'=> 1],
        ['name' => 'Corn Toasties','foodcategory_id'=> 1],
        ['name' => 'Cowboy Caviar (Bean Salsa)','foodcategory_id'=> 1],
        ['name' => 'Creamy Dill Dip','foodcategory_id'=> 1],
        ['name' => 'Creamy Vegetable Dip','foodcategory_id'=> 1],
        ['name' => 'Crispy Taquitos','foodcategory_id'=> 1],
        ['name' => 'Crunchy Vegetable Wraps','foodcategory_id'=> 1],
        ['name' => 'Cucumber Blueberry Salad','foodcategory_id'=> 1],
        ['name' => 'Cucumber Yogurt and Cream Cheese Dip','foodcategory_id'=> 1],
        ['name' => 'Cucumber, Yogurt and Herb Dip','foodcategory_id'=> 1],
        ['name' => 'Curry Vegetable Dip','foodcategory_id'=> 1],
        ['name' => 'Dave’s Herb-Stuffed Mushrooms','foodcategory_id'=> 1],
        ['name' => 'Deviled Eggs','foodcategory_id'=> 1],
        ['name' => 'Fiesta Hummus','foodcategory_id'=> 1],
        ['name' => 'Fiesta Lettuce Wraps and Pepper Boats','foodcategory_id'=> 1],
        ['name' => 'Fiesta Rice Salad','foodcategory_id'=> 1],
        ['name' => 'Fiesta Stuffed Avocado','foodcategory_id'=> 1],
        ['name' => 'Fruit & Feta Salad','foodcategory_id'=> 1],
        ['name' => 'Fruit and Peanut Butter Dip','foodcategory_id'=> 1],
        ['name' => 'Fruit Salsa','foodcategory_id'=> 1],
        ['name' => 'Grape Salsa','foodcategory_id'=> 1],
        ['name' => 'Grilled Vegetables','foodcategory_id'=> 1],
        ['name' => 'Hummus','foodcategory_id'=> 1],
        ['name' => 'Layered Black Bean Dip','foodcategory_id'=> 1],
        ['name' => 'Mango Salsa','foodcategory_id'=> 1],
        ['name' => 'Manhattan Clam Chowder','foodcategory_id'=> 1],
        ['name' => 'Mini Caprese Bites','foodcategory_id'=> 1],
        ['name' => 'Mozz Totz','foodcategory_id'=> 1],
        ['name' => 'Orange Glazed Skinless Chicken Wings','foodcategory_id'=> 1],
        ['name' => 'Oven-Fried Yucca','foodcategory_id'=> 1],
        ['name' => 'Pea Guacamole','foodcategory_id'=> 1],
        ['name' => 'Pear Quesadillas','foodcategory_id'=> 1],
        ['name' => 'Potato Cakes','foodcategory_id'=> 1],
        ['name' => 'Potato Nachos','foodcategory_id'=> 1],
        ['name' => 'Potato Skins with Buffalo Chicken','foodcategory_id'=> 1],
        ['name' => 'Pupusas Revueltas','foodcategory_id'=> 1],
        ['name' => 'Quick and Easy Bean Dip','foodcategory_id'=> 1],
        ['name' => 'Sardine, Cucumber, and Tomato Sandwich','foodcategory_id'=> 1],
        ['name' => 'Soft Pretzels','foodcategory_id'=> 1],
        ['name' => 'Southwestern Pepper Cups','foodcategory_id'=> 1],
        ['name' => 'Summer Salad','foodcategory_id'=> 1],
        ['name' => 'Sunshine Salad','foodcategory_id'=> 1],
        ['name' => 'Sweet and Juicy Raisin Tapenade','foodcategory_id'=> 1],
        ['name' => 'Sweet and Savory Peanut Butter Dip','foodcategory_id'=> 1],
        ['name' => 'Teriyaki Lettuce Wraps','foodcategory_id'=> 1],
        ['name' => 'Tomato Basil and Bean Pasta Salad','foodcategory_id'=> 1],
        ['name' => 'Tomato Basil Bruschetta','foodcategory_id'=> 1],
        ['name' => 'Tortilla Chips and Bean Dip','foodcategory_id'=> 1],
        ['name' => 'Tuna Veggie Antipasto','foodcategory_id'=> 1],
        ['name' => 'Turkey Pinwheel Appetizers','foodcategory_id'=> 1],
        ['name' => 'Turnip Pancakes','foodcategory_id'=> 1],
        ['name' => 'Vegetable Medley with Salsa Dip','foodcategory_id'=> 1],
        ['name' => 'Vegetarian Stuffed Peppers','foodcategory_id'=> 1],
        ['name' => 'Veggie Quesadillas','foodcategory_id'=> 1],
        ['name' => 'Waldorf Salad','foodcategory_id'=> 1],
        ['name' => 'White Bean Bruschetta','foodcategory_id'=> 1],
        ['name' => 'Whole Wheat Garlic Bread Sticks','foodcategory_id'=> 1],
            ['name' => 'Avocado Melon Breakfast Smoothie','foodcategory_id'=> 2],
            ['name' => 'Batido (Smoothie)','foodcategory_id'=> 2],
            ['name' => 'Cafe Mocha','foodcategory_id'=> 2],
            ['name' => 'Cantaloupe Cooler','foodcategory_id'=> 2],
            ['name' => 'Coffee Cooler','foodcategory_id'=> 2],
            ['name' => 'Flavored Water','foodcategory_id'=> 2],
            ['name' => 'Fruit and Yogurt Breakfast Shake','foodcategory_id'=> 2],
            ['name' => 'Fruit Juice Slush','foodcategory_id'=> 2],
            ['name' => 'Fruit Milk Shakes','foodcategory_id'=> 2],
            ['name' => 'Fruit Slush','foodcategory_id'=> 2],
            ['name' => 'Fruit Smoothie','foodcategory_id'=> 2],
            ['name' => 'Lemonade','foodcategory_id'=> 2],
            ['name' => 'Mango Shake','foodcategory_id'=> 2],
            ['name' => 'Orange Banana Frosty','foodcategory_id'=> 2],
            ['name' => 'Orange Cow','foodcategory_id'=> 2],
            ['name' => 'Orange Delight Juice','foodcategory_id'=> 2],
            ['name' => 'Peach Cooler','foodcategory_id'=> 2],
            ['name' => 'Peanut Butter Banana Breakfast Shake','foodcategory_id'=> 2],
            ['name' => 'Peanut Butter Banana Smoothie','foodcategory_id'=> 2],
            ['name' => 'Purple Cow','foodcategory_id'=> 2],
            ['name' => 'Summer Breeze Smoothie','foodcategory_id'=> 2],
            ['name' => 'Very Berry Smoothie','foodcategory_id'=> 2],

            ['name' => 'Apple Oatmeal Muffins','foodcategory_id'=> 3],
            ['name' => 'Banaha Bread','foodcategory_id'=> 3],
            ['name' => 'Banana Berry Muffins','foodcategory_id'=> 3],
            ['name' => 'Banana Bread','foodcategory_id'=> 3],
            ['name' => 'Basic Muffins','foodcategory_id'=> 3],
            ['name' => 'Blue Corn Pan Bread','foodcategory_id'=> 3],
            ['name' => 'Blueberry Coffee Cake','foodcategory_id'=> 3],
            ['name' => 'Blueberry Muffins','foodcategory_id'=> 3],
            ['name' => 'Bran Flake Raisin Muffins','foodcategory_id'=> 3],
            ['name' => 'Bran Muffins','foodcategory_id'=> 3],
            ['name' => 'Bread in a Bag','foodcategory_id'=> 3],
            ['name' => 'Chapatis Flatbread','foodcategory_id'=> 3],
            ['name' => 'Cinnamon Sugared Pumpkin Pecan Muffins','foodcategory_id'=> 3],
            ['name' => 'Corn Bread','foodcategory_id'=> 3],
            ['name' => 'Corn Toasties','foodcategory_id'=> 3],
            ['name' => 'Corn Tortillas','foodcategory_id'=> 3],
            ['name' => 'Cornmeal Pancakes','foodcategory_id'=> 3],
            ['name' => 'Cranberry Nut Bread','foodcategory_id'=> 3],
            ['name' => 'Cranberry Pumpkin Muffins','foodcategory_id'=> 3],
            ['name' => 'Drop Biscuits (from Better Baking Mix)','foodcategory_id'=> 3],
            ['name' => 'Fabulous Fruit Muffins','foodcategory_id'=> 3],
            ['name' => 'Feather Rolls','foodcategory_id'=> 3],
            ['name' => 'Flour Tortillas','foodcategory_id'=> 3],
            ['name' => 'Garden Pan Bread','foodcategory_id'=> 3],
            ['name' => 'Ginger Bread Mix','foodcategory_id'=> 3],
            ['name' => 'Ginger Orange Muffins','foodcategory_id'=> 3],
            ['name' => 'Homemade Bagles','foodcategory_id'=> 3],
            ['name' => 'Homemade Pizza Crust','foodcategory_id'=> 3],
            ['name' => 'Homestyle Biscuits','foodcategory_id'=> 3],
            ['name' => 'Lemon Corn Cake','foodcategory_id'=> 3],
            ['name' => 'Mixed Grain Bread','foodcategory_id'=> 3],
            ['name' => 'Muffins (from Better Baking Mix)','foodcategory_id'=> 3],
            ['name' => 'Naan','foodcategory_id'=> 3],
            ['name' => 'Oat Bran Muffins','foodcategory_id'=> 3],
            ['name' => 'Oat Snack Cakes','foodcategory_id'=> 3],
            ['name' => 'Oatmeal Bread','foodcategory_id'=> 3],
            ['name' => 'Oatmeal Raisin Muffins','foodcategory_id'=> 3],
            ['name' => 'Parmesan Chive Biscuits','foodcategory_id'=> 3],
            ['name' => 'Peanut Butter Bread','foodcategory_id'=> 3],
            ['name' => 'Peanut Butter Muffins','foodcategory_id'=> 3],
            ['name' => 'Perfect Pumpkin Pancakes','foodcategory_id'=> 3],
            ['name' => 'Pumpkin Bread','foodcategory_id'=> 3],
            ['name' => 'Pumpkin Chocolate Muffins','foodcategory_id'=> 3],
            ['name' => 'Soft Pretzels','foodcategory_id'=> 3],
            ['name' => 'Soul-Healthy Cornbread','foodcategory_id'=> 3],
            ['name' => 'Three-Grain Peanut Bread','foodcategory_id'=> 3],
            ['name' => 'Whole Wheat Garlic Bread Sticks','foodcategory_id'=> 3],
            ['name' => 'Whole Wheat Muffins','foodcategory_id'=> 3],
            ['name' => 'Wild Rice Muffins','foodcategory_id'=> 3],
            ['name' => 'Zucchini Bread','foodcategory_id'=> 3],




            ['name' => 'Apple Oatmeal Muffins','foodcategory_id'=> 4],
            ['name' => 'Apple Sandwiches','foodcategory_id'=> 4],
            ['name' => 'Apple Slice Pancakes','foodcategory_id'=> 4],
            ['name' => 'Apple Wedges with Pumpkin Almond Butter','foodcategory_id'=> 4],
            ['name' => 'Applesauce Pancakes','foodcategory_id'=> 4],
            ['name' => 'Avocado Breakfast Bruschetta','foodcategory_id'=> 4],
            ['name' => 'Avocado Melon Breakfast Smoothie','foodcategory_id'=> 4],
            ['name' => 'Banana Berry Muffins','foodcategory_id'=> 4],
            ['name' => 'Banana Oatmeal Pancakes with Lentils','foodcategory_id'=> 4],
            ['name' => 'Banana Pancakes with Apple Topping','foodcategory_id'=> 4],
            ['name' => 'Banana Split Oatmeal','foodcategory_id'=> 4],
            ['name' => 'Banana Waldorf','foodcategory_id'=> 4],
            ['name' => 'Banana Walnut Oatmeal','foodcategory_id'=> 4],
            ['name' => 'Basic Quiche','foodcategory_id'=> 4],
            ['name' => 'Batido (Smoothie)','foodcategory_id'=> 4],
            ['name' => 'Bell Pepper and Vidalia Onion Strata with Fresh Salsa','foodcategory_id'=> 4],
            ['name' => 'Black Bean Burrito','foodcategory_id'=> 4],
            ['name' => 'Blue Cornmeal Pancakes','foodcategory_id'=> 4],
            ['name' => 'Blueberry Coffee Cake','foodcategory_id'=> 4],
            ['name' => 'Blueberry Muffins','foodcategory_id'=> 4],
            ['name' => 'Bran Flake Raisin Muffins','foodcategory_id'=> 4],
            ['name' => 'Bran Muffins','foodcategory_id'=> 4],
            ['name' => 'Breakfast Parfait','foodcategory_id'=> 4],
            ['name' => 'Broccoli Omelet','foodcategory_id'=> 4],
            ['name' => 'Broccoli-Cheddar Frittata','foodcategory_id'=> 4],
            ['name' => 'Buttermilk Scones','foodcategory_id'=> 4],
            ['name' => 'Cherry Puff Pancake','foodcategory_id'=> 4],
            ['name' => 'Cinnamon Sugared Pumpkin Pecan Muffins','foodcategory_id'=> 4],
            ['name' => 'Cinnamon-Raisin Breakfast Mix','foodcategory_id'=> 4],
            ['name' => 'Coffee Cooler','foodcategory_id'=> 4],
            ['name' => 'Corn Casserole','foodcategory_id'=> 4],
            ['name' => 'Cornmeal Pancakes','foodcategory_id'=> 4],
            ['name' => 'Cranberry Pumpkin Muffins','foodcategory_id'=> 4],
            ['name' => 'Crunchy Berry Parfait','foodcategory_id'=> 4],
            ['name' => 'Eggs over Kale and Sweet Potato Grits','foodcategory_id'=> 4],
            ['name' => 'Fabulous Fruit Muffins','foodcategory_id'=> 4],
            ['name' => 'Fantastic French Toast','foodcategory_id'=> 4],
            ['name' => 'Fruit and Yogurt Breakfast Shake','foodcategory_id'=> 4],
            ['name' => 'Fruit Pizza To Go','foodcategory_id'=> 4],
            ['name' => 'Fruit Smoothie','foodcategory_id'=> 4],
            ['name' => 'Fruit Snake','foodcategory_id'=> 4],
            ['name' => 'Fruit Yogurt Parfait','foodcategory_id'=> 4],
            ['name' => 'Fruity Homemade Oatmeal','foodcategory_id'=> 4],
            ['name' => 'Garden Frittata','foodcategory_id'=> 4],
            ['name' => 'Ginger Orange Muffins','foodcategory_id'=> 4],
            ['name' => 'Granola Bars','foodcategory_id'=> 4],
            ['name' => 'Granola with Oatmeal, Coconut, and Pecans','foodcategory_id'=> 4],
            ['name' => 'Green Onion Omelet','foodcategory_id'=> 4],
            ['name' => 'Herbed Spinach Quiche Portabella Caps','foodcategory_id'=> 4],
            ['name' => 'Homemade Bagles','foodcategory_id'=> 4],
            ['name' => 'Hot Cornmeal Cereal','foodcategory_id'=> 4],
            ['name' => 'Huevos Motuleños','foodcategory_id'=> 4],
            ['name' => 'Jean’s Banana Pudding Parfait','foodcategory_id'=> 4],
            ['name' => 'Jiffy Oatmeal Crunch','foodcategory_id'=> 4],
            ['name' => 'Light as a Feather Whole Wheat Pancakes','foodcategory_id'=> 4],
            ['name' => 'Melon and Mint','foodcategory_id'=> 4],
            ['name' => 'Microwave Denver Scramble Slider','foodcategory_id'=> 4],
            ['name' => 'Muffins (from Better Baking Mix)','foodcategory_id'=> 4],
            ['name' => 'No Bake Breakfast Cookies','foodcategory_id'=> 4],
            ['name' => 'Oat Bran Muffins','foodcategory_id'=> 4],
            ['name' => 'Oat Snack Cakes','foodcategory_id'=> 4],
            ['name' => 'Oatmeal Bread','foodcategory_id'=> 4],
            ['name' => 'Oatmeal Raisin Muffins','foodcategory_id'=> 4],
            ['name' => 'Overnight Oatmeal','foodcategory_id'=> 4],
            ['name' => 'Overnight Oatmeal with Berries','foodcategory_id'=> 4],
            ['name' => 'Pancakes (from Better Baking Mix)','foodcategory_id'=> 4],
            ['name' => 'Peanut Butter Banana Breakfast Shake','foodcategory_id'=> 4],
            ['name' => 'Peanut Butter Cereal Bars','foodcategory_id'=> 4],
            ['name' => 'Peanut Butter Muffins','foodcategory_id'=> 4],
            ['name' => 'Perfect Pumpkin Pancakes','foodcategory_id'=> 4],
            ['name' => 'Pumpkin Chocolate Muffins','foodcategory_id'=> 4],
            ['name' => 'Pumpkin Cookies','foodcategory_id'=> 4],
            ['name' => 'Quesadilla con Huevos','foodcategory_id'=> 4],
            ['name' => 'Rice Bowl Breakfast with Fruit and Nuts','foodcategory_id'=> 4],
            ['name' => 'Rise and Shine Cobbler','foodcategory_id'=> 4],
            ['name' => 'Spanish Omelet','foodcategory_id'=> 4],
            ['name' => 'Springtime Cereal','foodcategory_id'=> 4],
            ['name' => 'Strawberry and Banana Fruit Smoothie','foodcategory_id'=> 4],
            ['name' => 'Strawberry Banana Parfait','foodcategory_id'=> 4],
            ['name' => 'Strawberry Mango Feta Toast Points','foodcategory_id'=> 4],
            ['name' => 'Summer Breeze Smoothie','foodcategory_id'=> 4],
            ['name' => 'Sure to Please Baked Eggs & Cheese','foodcategory_id'=> 4],
            ['name' => 'Sweet Potato Hash with Egg','foodcategory_id'=> 4],
            ['name' => 'Sweet Potato Pancakes with Balsamic Maple Mushrooms','foodcategory_id'=> 4],
            ['name' => 'Tomato and Garlic Omelet','foodcategory_id'=> 4],
            ['name' => 'Tropical Morning Treat','foodcategory_id'=> 4],
            ['name' => 'Tropical Overnight Oatmeal','foodcategory_id'=> 4],
            ['name' => 'Veggie Omelet in a Mug','foodcategory_id'=> 4],
            ['name' => 'Very Berry Muesli','foodcategory_id'=> 4],
            ['name' => 'Very Berry Smoothie','foodcategory_id'=> 4],
            ['name' => 'Whole Grain Strawberry Pancakes','foodcategory_id'=> 4],
            ['name' => 'Whole Wheat Muffins','foodcategory_id'=> 4],
            ['name' => 'Wild Rice Muffins','foodcategory_id'=> 4],
            ['name' => 'Yogurt Berry Parfait','foodcategory_id'=> 4],



            ['name' => 'Ambrosia','foodcategory_id'=> 5],
            ['name' => 'Angel Food Cake','foodcategory_id'=> 5],
            ['name' => 'Angel Food Pastry with Fresh Berries and Whipped Cream','foodcategory_id'=> 5],
            ['name' => 'Apple Cake','foodcategory_id'=> 5],
            ['name' => 'Apple Chunk Cake','foodcategory_id'=> 5],
            ['name' => 'Apple Cinnamon Bars','foodcategory_id'=> 5],
            ['name' => 'Apple Coffee Cake','foodcategory_id'=> 5],
            ['name' => 'Apple Crisp','foodcategory_id'=> 5],
            ['name' => 'Apple Pistachio Crisp','foodcategory_id'=> 5],
            ['name' => 'Apple Sandwiches','foodcategory_id'=> 5],
            ['name' => 'Apple Wedges with Pumpkin Almond Butter','foodcategory_id'=> 5],
            ['name' => 'Applesauce','foodcategory_id'=> 5],
            ['name' => 'Applesauce Cookies','foodcategory_id'=> 5],
            ['name' => 'Applesauce Loaf Cake','foodcategory_id'=> 5],
            ['name' => 'Baked Bananas','foodcategory_id'=> 5],
            ['name' => 'Banana Bread','foodcategory_id'=> 5],
            ['name' => 'Banana Cocoa Yogurt Pops','foodcategory_id'=> 5],
            ['name' => 'Banana Cupcakes','foodcategory_id'=> 5],
            ['name' => 'Banana Oat Cookies','foodcategory_id'=> 5],
            ['name' => 'Banana Oatmeal Raisin Cookies','foodcategory_id'=> 5],
            ['name' => 'Banana Pudding','foodcategory_id'=> 5],
            ['name' => 'Banana Waldorf','foodcategory_id'=> 5],
            ['name' => 'Bananas with Caramel Sauce','foodcategory_id'=> 5],
            ['name' => 'Basic Custard','foodcategory_id'=> 5],
            ['name' => 'Berries with Banana Cream','foodcategory_id'=> 5],
            ['name' => 'Berry Bread Pudding','foodcategory_id'=> 5],
            ['name' => 'Berry Good Dessert','foodcategory_id'=> 5],
            ['name' => 'Bread Pudding with Vanilla Sauce','foodcategory_id'=> 5],
            ['name' => 'Buttermilk Scones','foodcategory_id'=> 5],
            ['name' => 'Caramel Sauce','foodcategory_id'=> 5],
            ['name' => 'Carrot Cookies','foodcategory_id'=> 5],
            ['name' => 'Cherry Puff Pancake','foodcategory_id'=> 5],
            ['name' => 'Cherry, Melon, & Grape Salad','foodcategory_id'=> 5],
            ['name' => 'Chocolate Chip Yogurt Cookies','foodcategory_id'=> 5],
            ['name' => 'Chocolate Peanut Butter Frozen Bars','foodcategory_id'=> 5],
            ['name' => 'Chocolate Squash Cake','foodcategory_id'=> 5],
            ['name' => 'Classic Honey Flan','foodcategory_id'=> 5],
            ['name' => 'Cran-Apple Crisp','foodcategory_id'=> 5],
            ['name' => 'Cranberry Nut Bread','foodcategory_id'=> 5],
            ['name' => 'Cranberry Wojapi','foodcategory_id'=> 5],
            ['name' => 'Crunchy Berry Parfait','foodcategory_id'=> 5],
            ['name' => 'Crustless Pumpkin Pie','foodcategory_id'=> 5],
            ['name' => 'Deep Dish Apple Cranberry Pie','foodcategory_id'=> 5],
            ['name' => 'Dutch Apple Yogurt Dessert','foodcategory_id'=> 5],
            ['name' => 'Easiest Banana Ice Cream','foodcategory_id'=> 5],
            ['name' => 'Fabulous Fig Bars','foodcategory_id'=> 5],
            ['name' => 'Fat-Free Apple Crumb Dessert','foodcategory_id'=> 5],
            ['name' => 'Festive Microwave Baked Apples','foodcategory_id'=> 5],
            ['name' => 'Fresh Fruit with Cinnamon Yogurt Dip','foodcategory_id'=> 5],
            ['name' => 'Frosted Cake','foodcategory_id'=> 5],
            ['name' => 'Frozen Banana Pops','foodcategory_id'=> 5],
            ['name' => 'Frozen Fruit Cups','foodcategory_id'=> 5],
            ['name' => 'Frozen Fruit Pops','foodcategory_id'=> 5],
            ['name' => 'Fruit Compote','foodcategory_id'=> 5],
            ['name' => 'Fruit Crisp','foodcategory_id'=> 5],
            ['name' => 'Fruit Dip','foodcategory_id'=> 5],
            ['name' => 'Fruit Dippers','foodcategory_id'=> 5],
            ['name' => 'Fruit Juice Slush','foodcategory_id'=> 5],
            ['name' => 'Fruit Kabob','foodcategory_id'=> 5],
            ['name' => 'Fruit Milk Shakes','foodcategory_id'=> 5],
            ['name' => 'Fruit Pizza','foodcategory_id'=> 5],
            ['name' => 'Fruit Salad with Yogurt','foodcategory_id'=> 5],
            ['name' => 'Fruit Salsa','foodcategory_id'=> 5],
            ['name' => 'Fruit Slush','foodcategory_id'=> 5],
            ['name' => 'Fruit Sorbet','foodcategory_id'=> 5],
            ['name' => 'Fruit Yogurt Parfait','foodcategory_id'=> 5],
            ['name' => 'Fruit Yogurt Pops','foodcategory_id'=> 5],
            ['name' => 'Fudgy Fruit','foodcategory_id'=> 5],
            ['name' => 'Grilled Fruit','foodcategory_id'=> 5],
            ['name' => 'Honey Milk Balls','foodcategory_id'=> 5],
            ['name' => 'Honeydew Summer Salad Wedges','foodcategory_id'=> 5],
            ['name' => 'Instant Chocolate Mousse','foodcategory_id'=> 5],
            ['name' => 'Jean’s Banana Pudding Parfait','foodcategory_id'=> 5],
            ['name' => 'Jiffy Oatmeal Crunch','foodcategory_id'=> 5],
            ['name' => 'Lemon Corn Cake','foodcategory_id'=> 5],
            ['name' => 'Lemon Velvet Supreme','foodcategory_id'=> 5],
            ['name' => 'Magical Fruit Salad','foodcategory_id'=> 5],
            ['name' => 'Mango Shake','foodcategory_id'=> 5],
            ['name' => 'Matzo Meal Kugel (Pudding)','foodcategory_id'=> 5],
            ['name' => 'Melon and Mint','foodcategory_id'=> 5],
            ['name' => 'Mock Southern Sweet Potato Pie','foodcategory_id'=> 5],
            ['name' => 'Mousse a la Banana','foodcategory_id'=> 5],
            ['name' => 'No Bake Breakfast Cookies','foodcategory_id'=> 5],
            ['name' => 'No-Bake Cookies','foodcategory_id'=> 5],
            ['name' => 'Old Fashioned Bread Pudding','foodcategory_id'=> 5],
            ['name' => 'Orange Delight Juice','foodcategory_id'=> 5],
            ['name' => 'Passover Rhubarb Cobbler','foodcategory_id'=> 5],
            ['name' => 'Peach Apple Crisp','foodcategory_id'=> 5],
            ['name' => 'Peach Crisp','foodcategory_id'=> 5],
            ['name' => 'Peachy Peanut Butter Pita Pockets','foodcategory_id'=> 5],
            ['name' => 'Peachy Pops','foodcategory_id'=> 5],
            ['name' => 'Peanut Butter Banana Smoothie','foodcategory_id'=> 5],
            ['name' => 'Peanut Butter Cereal Bars','foodcategory_id'=> 5],
            ['name' => 'Pear in Orange Sauce','foodcategory_id'=> 5],
            ['name' => 'Pear Kabobs with Strawberry Dipping Sauce','foodcategory_id'=> 5],
            ['name' => 'Pear Party Salsa','foodcategory_id'=> 5],
            ['name' => 'Peter Pumpkin Squares','foodcategory_id'=> 5],
            ['name' => 'Pineapple Angel Food Cake','foodcategory_id'=> 5],
            ['name' => 'Pineapple Orange Frozen Yogurt','foodcategory_id'=> 5],
            ['name' => 'Pineapple Rice Bake','foodcategory_id'=> 5],
            ['name' => 'Pocket Fruit Pies','foodcategory_id'=> 5],
            ['name' => 'Popcorn Treats','foodcategory_id'=> 5],
            ['name' => 'Pumpkin Angel Food Cake','foodcategory_id'=> 5],
            ['name' => 'Pumpkin Bread','foodcategory_id'=> 5],
            ['name' => 'Pumpkin Cheese Pie','foodcategory_id'=> 5],
            ['name' => 'Pumpkin Chocolate Muffins','foodcategory_id'=> 5],
            ['name' => 'Pumpkin Cookies','foodcategory_id'=> 5],
            ['name' => 'Pumpkin Pudding','foodcategory_id'=> 5],
            ['name' => 'Quick Peach Cobbler','foodcategory_id'=> 5],
            ['name' => 'Rhubarb Blueberry Crisp','foodcategory_id'=> 5],
            ['name' => 'Rice Dessert','foodcategory_id'=> 5],
            ['name' => 'Rice Pudding','foodcategory_id'=> 5],
            ['name' => 'Rice Pudding','foodcategory_id'=> 5],
            ['name' => 'Shake-A-Pudding','foodcategory_id'=> 5],
            ['name' => 'Southern Banana Pudding','foodcategory_id'=> 5],
            ['name' => 'Spicy Fruit Cup','foodcategory_id'=> 5],
            ['name' => 'Squash-Apple Casserole','foodcategory_id'=> 5],
            ['name' => 'Strawberry Banana Parfait','foodcategory_id'=> 5],
            ['name' => 'Strawberry Kiwi Yogurt Pops','foodcategory_id'=> 5],
            ['name' => 'Strawberry SMores','foodcategory_id'=> 5],
            ['name' => 'Strawberry Yogurt Pops','foodcategory_id'=> 5],
            ['name' => 'Sugar and Spice Cookies (from Better Baking Mix)','foodcategory_id'=> 5],
            ['name' => 'Summer Breeze Smoothie','foodcategory_id'=> 5],
            ['name' => 'Summer Fruit Salad','foodcategory_id'=> 5],
            ['name' => 'Sweet Cornmeal Pudding with Ginger and Cinnamon','foodcategory_id'=> 5],
            ['name' => 'Sweet Potato and Apple Bake','foodcategory_id'=> 5],
            ['name' => 'Sweet Potato Casserole','foodcategory_id'=> 5],
            ['name' => 'Sweet Potato Cheesecake','foodcategory_id'=> 5],
            ['name' => 'Sweet Potato Custard','foodcategory_id'=> 5],
            ['name' => 'Sweet Potato Pie','foodcategory_id'=> 5],
            ['name' => 'Sweet Potato Pone','foodcategory_id'=> 5],
            ['name' => 'Tropical Yogurt Pops','foodcategory_id'=> 5],
            ['name' => 'Very Berry Muesli','foodcategory_id'=> 5],
            ['name' => 'Very Berry Smoothie','foodcategory_id'=> 5],
            ['name' => 'Winter Crisp','foodcategory_id'=> 5],
            ['name' => 'Wobbly Wonders','foodcategory_id'=> 5],
            ['name' => 'Yogurt Berry Parfait','foodcategory_id'=> 5],
            ['name' => 'Yogurt Pops','foodcategory_id'=> 5],
            ['name' => 'Yogurt Popsicles','foodcategory_id'=> 5],
            ['name' => 'Zucchini Bread','foodcategory_id'=> 5],





            ['name' => '2-Step Chicken','foodcategory_id'=> 6],
            ['name' => '20-Minute Chicken Creole','foodcategory_id'=> 6],
            ['name' => 'Any Days a Picnic Chicken Salad','foodcategory_id'=> 6],
            ['name' => 'Anytime Pizza','foodcategory_id'=> 6],
            ['name' => 'Apple Carrot Soup','foodcategory_id'=> 6],
            ['name' => 'Apple, Fennel & Chicken Salad with Couscous','foodcategory_id'=> 6],
            ['name' => 'Apricot & Lemon Chicken','foodcategory_id'=> 6],
            ['name' => 'Argentinean Grilled Steak with Salsa Criolla','foodcategory_id'=> 6],
            ['name' => 'Arroz Con Pollo','foodcategory_id'=> 6],
            ['name' => 'Arroz Con Pollo (Chicken and Rice)','foodcategory_id'=> 6],
            ['name' => 'Asian Mango Chicken Wraps','foodcategory_id'=> 6],
            ['name' => 'Avocado, Potato, and Grilled Chicken Salad','foodcategory_id'=> 6],
            ['name' => 'Baked Chicken','foodcategory_id'=> 6],
            ['name' => 'Baked Chicken Nuggets','foodcategory_id'=> 6],
            ['name' => 'Baked Chicken with Vegetables','foodcategory_id'=> 6],
            ['name' => 'Baked Fish','foodcategory_id'=> 6],
            ['name' => 'Baked Fish and Vegetables','foodcategory_id'=> 6],
            ['name' => 'Baked Fish with Creole Sauce','foodcategory_id'=> 6],
            ['name' => 'Baked Lemon Chicken','foodcategory_id'=> 6],
            ['name' => 'Baked Lentils Casserole','foodcategory_id'=> 6],
            ['name' => 'Baked Meatballs','foodcategory_id'=> 6],
            ['name' => 'Baked Parmesan Fish','foodcategory_id'=> 6],
            ['name' => 'Baked Pork Chops','foodcategory_id'=> 6],
            ['name' => 'Baked Tofu','foodcategory_id'=> 6],
            ['name' => 'Baked Trout','foodcategory_id'=> 6],
            ['name' => 'Barley Jambalaya','foodcategory_id'=> 6],
            ['name' => 'Basic Quiche','foodcategory_id'=> 6],
            ['name' => 'BBQ Chicken Pizza','foodcategory_id'=> 6],
            ['name' => 'Bean and Rice Burritos','foodcategory_id'=> 6],
            ['name' => 'Bean Enchiladas','foodcategory_id'=> 6],
            ['name' => 'Beef & Noodles','foodcategory_id'=> 6],
            ['name' => 'Beef & Potatoes','foodcategory_id'=> 6],
            ['name' => 'Beef and Bean Chile Verde','foodcategory_id'=> 6],
            ['name' => 'Beef and Cabbage','foodcategory_id'=> 6],
            ['name' => 'Beef and Vegetables','foodcategory_id'=> 6],
            ['name' => 'Beef Pot Roast','foodcategory_id'=> 6],
            ['name' => 'Beef Pozole Soup','foodcategory_id'=> 6],
            ['name' => 'Beef Stroganoff','foodcategory_id'=> 6],
            ['name' => 'Beefy Macaroni and Cheese','foodcategory_id'=> 6],
            ['name' => 'Bell Pepper Nachos','foodcategory_id'=> 6],
            ['name' => 'Black Bean and Rice Salad','foodcategory_id'=> 6],
            ['name' => 'Black Bean and Sweet Potato Quesadillas','foodcategory_id'=> 6],
            ['name' => 'Black Bean Burgers','foodcategory_id'=> 6],
            ['name' => 'Black Bean Quesadillas','foodcategory_id'=> 6],
            ['name' => 'Black Bean Soup','foodcategory_id'=> 6],
            ['name' => 'Black Beans','foodcategory_id'=> 6],
            ['name' => 'Black Skillet Beef with Greens and Red Potatoes','foodcategory_id'=> 6],
            ['name' => 'Braised Chicken Thighs with Spinach','foodcategory_id'=> 6],
            ['name' => 'Brazilian Rice','foodcategory_id'=> 6],
            ['name' => 'Bread Bake with Chicken, Cheese, and Vegetables','foodcategory_id'=> 6],
            ['name' => 'Breakfast Burrito with Salsa','foodcategory_id'=> 6],
            ['name' => 'Brilliant Chili Topped with Walnuts','foodcategory_id'=> 6],
            ['name' => 'Broccoli Alfredo','foodcategory_id'=> 6],
            ['name' => 'Broccoli Omelet','foodcategory_id'=> 6],
            ['name' => 'Broccoli Rice Casserole','foodcategory_id'=> 6],
            ['name' => 'Bronco Beans','foodcategory_id'=> 6],
            ['name' => 'Brown Rice Pilaf with Sage, Walnuts, and Dried Fruit','foodcategory_id'=> 6],
            ['name' => 'Brown Rice with Sizzling Chicken and Vegetables','foodcategory_id'=> 6],
            ['name' => 'Bulgur Wheat, Veggie & Chickpea Salad','foodcategory_id'=> 6],
            ['name' => 'Butternut Squash Pasta Bake','foodcategory_id'=> 6],
            ['name' => 'Butternut Squash with Black Beans','foodcategory_id'=> 6],
            ['name' => 'Cabbage Roll Casserole','foodcategory_id'=> 6],
            ['name' => 'Cajun Catfish','foodcategory_id'=> 6],
            ['name' => 'Caribbean Casserole','foodcategory_id'=> 6],
            ['name' => 'Caribbean Pink Beans','foodcategory_id'=> 6],
            ['name' => 'Carrots with Tomatoes and Macaroni','foodcategory_id'=> 6],
            ['name' => 'Catfish Stew and Rice','foodcategory_id'=> 6],
            ['name' => 'Cauliflower Shells with Cheese','foodcategory_id'=> 6],
            ['name' => 'Cheese-A-Roni Bake','foodcategory_id'=> 6],
            ['name' => 'Cheesy Chicken, Broccoli, and Rice Bake','foodcategory_id'=> 6],
            ['name' => 'Chicken and Beans','foodcategory_id'=> 6],
            ['name' => 'Chicken and Broccoli Bake','foodcategory_id'=> 6],
            ['name' => 'Chicken and Cranberry Salad','foodcategory_id'=> 6],
            ['name' => 'Chicken and Dumpling Soup','foodcategory_id'=> 6],
            ['name' => 'Chicken and Dumplings','foodcategory_id'=> 6],
            ['name' => 'Chicken and Spanish Rice','foodcategory_id'=> 6],
            ['name' => 'Chicken Broccoli Alfredo','foodcategory_id'=> 6],
            ['name' => 'Chicken Cacciatore','foodcategory_id'=> 6],
            ['name' => 'Chicken Casserole','foodcategory_id'=> 6],
            ['name' => 'Chicken Club Salad','foodcategory_id'=> 6],
            ['name' => 'Chicken Mole','foodcategory_id'=> 6],
            ['name' => 'Chicken Pasta Salad','foodcategory_id'=> 6],
            ['name' => 'Chicken Pot Pie','foodcategory_id'=> 6],
            ['name' => 'Chicken Ratatouille','foodcategory_id'=> 6],
            ['name' => 'Chicken Soup with Chiles','foodcategory_id'=> 6],
            ['name' => 'Chicken Spaghetti','foodcategory_id'=> 6],
            ['name' => 'Chicken Spanish Rice','foodcategory_id'=> 6],
            ['name' => 'Chicken Stew','foodcategory_id'=> 6],
            ['name' => 'Chicken Stir-Fry','foodcategory_id'=> 6],
            ['name' => 'Chicken Tortilla Casserole','foodcategory_id'=> 6],
            ['name' => 'Chicken Waldorf Salad','foodcategory_id'=> 6],
            ['name' => 'Chicken, Rice, and Fruit Salad','foodcategory_id'=> 6],
            ['name' => 'Chickpeas and Spinach Sauté','foodcategory_id'=> 6],
            ['name' => 'Chili Cheese Hominy','foodcategory_id'=> 6],
            ['name' => 'Chili Tomato Macaroni','foodcategory_id'=> 6],
            ['name' => 'Citrus Chicken','foodcategory_id'=> 6],
            ['name' => 'Citrus Salmon Fillets','foodcategory_id'=> 6],
            ['name' => 'Citrus Tuna Melt','foodcategory_id'=> 6],
            ['name' => 'Cobb Salad with Pears','foodcategory_id'=> 6],
            ['name' => 'Collard Green Gumbo with Ham Hock','foodcategory_id'=> 6],
            ['name' => 'Colorful Quesadillas','foodcategory_id'=> 6],
            ['name' => 'Creamy Chicken Hash','foodcategory_id'=> 6],
            ['name' => 'Crispy Oven-Fried Chicken','foodcategory_id'=> 6],
            ['name' => 'Crispy Taquitos','foodcategory_id'=> 6],
            ['name' => 'Crispy Walleye Patties','foodcategory_id'=> 6],
            ['name' => 'Crunchy Chicken Salad','foodcategory_id'=> 6],
            ['name' => 'Crusty Rice with Tofu and Vegetables','foodcategory_id'=> 6],
            ['name' => 'Cuban Beans and Rice','foodcategory_id'=> 6],
            ['name' => 'Cumin Lime Shrimp over Creamy Cauliflower Risotto','foodcategory_id'=> 6],
            ['name' => 'Curried Chicken with Raisins and Mushrooms','foodcategory_id'=> 6],
            ['name' => 'Curried Chickpea Salad','foodcategory_id'=> 6],
            ['name' => 'Dilled Fish Fillets','foodcategory_id'=> 6],
            ['name' => 'Easy Beef Supper','foodcategory_id'=> 6],
            ['name' => 'Easy Oven Fish with Spinach Basil Dipping Sauce & Spiced Apples','foodcategory_id'=> 6],
            ['name' => 'Easy Oven Packet Caribbean Tilapia with Pears and Carnival Roasted Potatoes','foodcategory_id'=> 6],
            ['name' => 'Easy-As-A-Mix Pizza (from Better Baking Mix)','foodcategory_id'=> 6],
            ['name' => 'Egg Foo Young','foodcategory_id'=> 6],
            ['name' => 'Eggplant Stir Fry','foodcategory_id'=> 6],
            ['name' => 'Eggs over Kale and Sweet Potato Grits','foodcategory_id'=> 6],
            ['name' => 'Enchilada Bake','foodcategory_id'=> 6],
            ['name' => 'Enchilada Rice','foodcategory_id'=> 6],
            ['name' => 'European Salad','foodcategory_id'=> 6],
            ['name' => 'Eve s Tasty Turkey Tetrazzini','foodcategory_id'=> 6],
            ['name' => 'Falafel with Yogurt Sandwich','foodcategory_id'=> 6],
            ['name' => 'Fall Veggie Casserole','foodcategory_id'=> 6],
            ['name' => 'Fantastic French Toast','foodcategory_id'=> 6],
            ['name' => 'Fiesta Lettuce Wraps and Pepper Boats','foodcategory_id'=> 6],
            ['name' => 'Fiesta Rice Salad','foodcategory_id'=> 6],
            ['name' => 'Fish Tacos','foodcategory_id'=> 6],
            ['name' => 'Fish with Spinach','foodcategory_id'=> 6],
            ['name' => 'Five Happiness Fried Noodles','foodcategory_id'=> 6],
            ['name' => 'Flavorful Fried Rice','foodcategory_id'=> 6],
            ['name' => 'Four Layer Casserole','foodcategory_id'=> 6],
            ['name' => 'Fried Rice','foodcategory_id'=> 6],
            ['name' => 'Fried Rice','foodcategory_id'=> 6],
            ['name' => 'Full of Beans Hot Dish','foodcategory_id'=> 6],
            ['name' => 'Garden Cannellini Bean Salad','foodcategory_id'=> 6],
            ['name' => 'Garden Chili','foodcategory_id'=> 6],
            ['name' => 'Garlic Ginger Ramen with Beef','foodcategory_id'=> 6],
            ['name' => 'Garlic Stuffed Chicken','foodcategory_id'=> 6],
            ['name' => 'Gingery Quinoa with Green Beans','foodcategory_id'=> 6],
            ['name' => 'Glazed Meatloaf','foodcategory_id'=> 6],
            ['name' => 'Greek Pork Chops','foodcategory_id'=> 6],
            ['name' => 'Grilled Asparagus and Shrimp Quinoa Salad with Lemon Vinaigrette','foodcategory_id'=> 6],
            ['name' => 'Grilled Cheese with Peaches','foodcategory_id'=> 6],
            ['name' => 'Grilled Chicken and Avocado Quinoa Pilaf','foodcategory_id'=> 6],
            ['name' => 'Grilled Fish Tacos with Peach Salsa','foodcategory_id'=> 6],
            ['name' => 'Grilled Lamb Salad','foodcategory_id'=> 6],
            ['name' => 'Grilled Pineapple Ginger Glazed Chicken with Zucchini and Peppers','foodcategory_id'=> 6],
            ['name' => 'Grilled Shrimp with Cantaloupe Avocado Salsa','foodcategory_id'=> 6],
            ['name' => 'Grilled Steak and Peppers Salad with Pears','foodcategory_id'=> 6],
            ['name' => 'Hearty Salmon Skewers over Brown Rice','foodcategory_id'=> 6],
            ['name' => 'Hearty Vegetable Beef Soup','foodcategory_id'=> 6],
            ['name' => 'Herb Broiled Beef','foodcategory_id'=> 6],
            ['name' => 'Herbed Lentils and Rice Casserole','foodcategory_id'=> 6],
            ['name' => 'Honey Lemon Chicken','foodcategory_id'=> 6],
            ['name' => 'Honey Mustard Pork Chops','foodcategory_id'=> 6],
            ['name' => 'Hooked on Salmon Sticks','foodcategory_id'=> 6],
            ['name' => 'Hoppin John (Sausage, Black-Eyed Peas, and Rice)','foodcategory_id'=> 6],
            ['name' => 'Hot-Wing-Flavored Chicken with Ranch Sauce','foodcategory_id'=> 6],
            ['name' => 'Huevos Rancheros with Fresh Salsa','foodcategory_id'=> 6],
            ['name' => 'Italian Bean Patties','foodcategory_id'=> 6],
            ['name' => 'Italian Broccoli and Pasta','foodcategory_id'=> 6],
            ['name' => 'Jamaican Jerk Chicken','foodcategory_id'=> 6],
            ['name' => 'Jollof Rice','foodcategory_id'=> 6],
            ['name' => 'Kibbeh Khamoustah','foodcategory_id'=> 6],
            ['name' => 'Leafy Tofu','foodcategory_id'=> 6],
            ['name' => 'Leftover Turkey Casserole','foodcategory_id'=> 6],
            ['name' => 'Lemon Pepper Salmon Patties','foodcategory_id'=> 6],
            ['name' => 'Lentil Spaghetti Sauce','foodcategory_id'=> 6],
            ['name' => 'Lentil Stew','foodcategory_id'=> 6],
            ['name' => 'Lentil Tacos','foodcategory_id'=> 6],
            ['name' => 'Mac and Beans Medley','foodcategory_id'=> 6],
            ['name' => 'Macaroni & Cheese with Broccoli','foodcategory_id'=> 6],
            ['name' => 'Magic Crust Quiche','foodcategory_id'=> 6],
            ['name' => 'Main Dish Salad','foodcategory_id'=> 6],
            ['name' => 'Manhattan Clam Chowder','foodcategory_id'=> 6],
            ['name' => 'Marinated Beef','foodcategory_id'=> 6],
            ['name' => 'Meatball Soup','foodcategory_id'=> 6],
            ['name' => 'Meatloaf','foodcategory_id'=> 6],
            ['name' => 'Meatloaf in a Mug','foodcategory_id'=> 6],
            ['name' => 'Meaty Stuffed Potatoes','foodcategory_id'=> 6],
            ['name' => 'Mediterranean Roasted Eggplant with Tomato Sauce','foodcategory_id'=> 6],
            ['name' => 'Mediterranean Tuna Antipasti Salad','foodcategory_id'=> 6],
            ['name' => 'Migas "Crumbs"','foodcategory_id'=> 6],
            ['name' => 'Mouth-Watering Oven-Fried Fish','foodcategory_id'=> 6],
            ['name' => 'Mozzarella Chicken with Garlic Spinach','foodcategory_id'=> 6],
            ['name' => 'Mushroom Beef Sloppy Joes','foodcategory_id'=> 6],
            ['name' => 'Mushroom Steak Fajitas','foodcategory_id'=> 6],
            ['name' => 'Neopolitan Tuna Fettuccine','foodcategory_id'=> 6],
            ['name' => 'New Orleans Red Beans','foodcategory_id'=> 6],
            ['name' => 'One Pan Potatoes & Chicken','foodcategory_id'=> 6],
            ['name' => 'One Pan Spaghetti','foodcategory_id'=> 6],
            ['name' => 'One Pan Taco Rice','foodcategory_id'=> 6],
            ['name' => 'One-Dish Roasted Potatoes and Apples with Chicken Sausage','foodcategory_id'=> 6],
            ['name' => 'Orange Pork Chops','foodcategory_id'=> 6],
            ['name' => 'Oven Fried Fish','foodcategory_id'=> 6],
            ['name' => 'Oven Roasted Chicken','foodcategory_id'=> 6],
            ['name' => 'Pan Roasted Tilapia with Tomatillo Salsa','foodcategory_id'=> 6],
            ['name' => 'Party-Time Pasta','foodcategory_id'=> 6],
            ['name' => 'Pasta Bolognese','foodcategory_id'=> 6],
            ['name' => 'Pasta Frittata with Peas','foodcategory_id'=> 6],
            ['name' => 'Pasta Primavera','foodcategory_id'=> 6],
            ['name' => 'Pasta Primavera II','foodcategory_id'=> 6],
            ['name' => 'Pasta with Chickpeas, Tomato, and Spinach','foodcategory_id'=> 6],
            ['name' => 'Pasta with Greens, Beans, and Chicken','foodcategory_id'=> 6],
            ['name' => 'Pasta with Vegetables','foodcategory_id'=> 6],
            ['name' => 'Peanutty Stew','foodcategory_id'=> 6],
            ['name' => 'Pear Quesadillas','foodcategory_id'=> 6],
            ['name' => 'Picadillo','foodcategory_id'=> 6],
            ['name' => 'Picadillo','foodcategory_id'=> 6],
            ['name' => 'Pineapple Avocado Chicken Salad','foodcategory_id'=> 6],
            ['name' => 'Pineapple Chicken','foodcategory_id'=> 6],
            ['name' => 'Pineapple Pork','foodcategory_id'=> 6],
            ['name' => 'Pizza Meat Loaf','foodcategory_id'=> 6],
            ['name' => 'Plantain Cups with Shredded Chicken | Mofonguitos','foodcategory_id'=> 6],
            ['name' => 'Polenta with Pepper and Cheese','foodcategory_id'=> 6],
            ['name' => 'Pork Loin Roast with Veggies','foodcategory_id'=> 6],
            ['name' => 'Pot Roasted Beef','foodcategory_id'=> 6],
            ['name' => 'Potato Beef Casserole','foodcategory_id'=> 6],
            ['name' => 'Potato Nachos','foodcategory_id'=> 6],
            ['name' => 'Potato Skins with Buffalo Chicken','foodcategory_id'=> 6],
            ['name' => 'Potato, Black Bean, & Kale Skillet','foodcategory_id'=> 6],
            ['name' => 'Pulled Pork Sandwich with Red Cabbage and Carrot Slaw','foodcategory_id'=> 6],
            ['name' => 'Pumpkin Chili','foodcategory_id'=> 6],
            ['name' => 'Pumpkin Mac & Cheese for One','foodcategory_id'=> 6],
            ['name' => 'Pumpkin Ricotta Stuffed Shells','foodcategory_id'=> 6],
            ['name' => 'Pupusas Revueltas','foodcategory_id'=> 6],
            ['name' => 'Quesadilla con Huevos','foodcategory_id'=> 6],
            ['name' => 'Quick N Cool Summer Salad','foodcategory_id'=> 6],
            ['name' => 'Quick and Healthy Black-Eyed Peas','foodcategory_id'=> 6],
            ['name' => 'Quick Skillet Lasagna','foodcategory_id'=> 6],
            ['name' => 'Quick Tuna Casserole','foodcategory_id'=> 6],
            ['name' => 'Quinoa and Black Bean Salad','foodcategory_id'=> 6],
            ['name' => 'Red Bean Quesadilla','foodcategory_id'=> 6],
            ['name' => 'Red Beans and Rice','foodcategory_id'=> 6],
            ['name' => 'Red Beans and Rice','foodcategory_id'=> 6],
            ['name' => 'Red Beans and Rice','foodcategory_id'=> 6],
            ['name' => 'Red Hot Fusilli','foodcategory_id'=> 6],
            ['name' => 'Rice-Crusted Pizza','foodcategory_id'=> 6],
            ['name' => 'Roast Chicken','foodcategory_id'=> 6],
            ['name' => 'Roast Turkey Breast with Rosemary, Sage, and Thyme','foodcategory_id'=> 6],
            ['name' => 'Roasted Brussels Sprouts, Potatoes, and Chicken','foodcategory_id'=> 6],
            ['name' => 'Round Steak Casserole','foodcategory_id'=> 6],
            ['name' => 'Salmon Burgers','foodcategory_id'=> 6],
            ['name' => 'Salmon Burgers and Sweet Potato Oven Fries','foodcategory_id'=> 6],
            ['name' => 'Salmon Loaf','foodcategory_id'=> 6],
            ['name' => 'Salmon Patties','foodcategory_id'=> 6],
            ['name' => 'Savory and Spicy Ground Beef & Succotash','foodcategory_id'=> 6],
            ['name' => 'Savory Meatloaf Muffins','foodcategory_id'=> 6],
            ['name' => 'Scrambled Tofu','foodcategory_id'=> 6],
            ['name' => 'Sensational Six-Layer Dinner','foodcategory_id'=> 6],
            ['name' => 'Shepherds Pie','foodcategory_id'=> 6],
            ['name' => 'Short Cut Lasagna','foodcategory_id'=> 6],
            ['name' => 'Simple Fish Tacos','foodcategory_id'=> 6],
            ['name' => 'Simple Stuffed Peppers','foodcategory_id'=> 6],
            ['name' => 'Simply Satisfying Kale and Tuna Salad','foodcategory_id'=> 6],
            ['name' => 'Skillet Catfish','foodcategory_id'=> 6],
            ['name' => 'Skillet Lasagna','foodcategory_id'=> 6],
            ['name' => 'Skillet Meals','foodcategory_id'=> 6],
            ['name' => 'Skillet Noodles and Beef','foodcategory_id'=> 6],
            ['name' => 'Skillet Pasta Dinner','foodcategory_id'=> 6],
            ['name' => 'Skillet-Braised Chicken','foodcategory_id'=> 6],
            ['name' => 'Sloppy Garden Joes','foodcategory_id'=> 6],
            ['name' => 'Slow Cooker Beef Stew','foodcategory_id'=> 6],
            ['name' => 'Slow Cooker Cheesy Swiss Steak','foodcategory_id'=> 6],
            ['name' => 'Slow Cooker Hamburger Stew','foodcategory_id'=> 6],
            ['name' => 'Slow Cooker Pork Stew over Brown Rice','foodcategory_id'=> 6],
            ['name' => 'Slow-Cook Barbecue','foodcategory_id'=> 6],
            ['name' => 'Smoky Mustard-Maple Salmon','foodcategory_id'=> 6],
            ['name' => 'Snappy Rice Dish','foodcategory_id'=> 6],
            ['name' => 'Soft Chicken Taco','foodcategory_id'=> 6],
            ['name' => 'Soy Marinated Chicken','foodcategory_id'=> 6],
            ['name' => 'Spaghetti and Spinach Pesto','foodcategory_id'=> 6],
            ['name' => 'Spaghetti with Quick Meat Sauce','foodcategory_id'=> 6],
            ['name' => 'Spanish Baked Fish','foodcategory_id'=> 6],
            ['name' => 'Spanish Frittata','foodcategory_id'=> 6],
            ['name' => 'Spanish Omelet','foodcategory_id'=> 6],
            ['name' => 'Speedy Burritos','foodcategory_id'=> 6],
            ['name' => 'Spicy Baked Fish','foodcategory_id'=> 6],
            ['name' => 'Spicy Baked Fish II','foodcategory_id'=> 6],
            ['name' => 'Spicy Chicken and Potato Soup','foodcategory_id'=> 6],
            ['name' => 'Spicy Oven-Baked Chicken','foodcategory_id'=> 6],
            ['name' => 'Spicy Southern Barbecued Chicken','foodcategory_id'=> 6],
            ['name' => 'Spinach and Meat Cakes','foodcategory_id'=> 6],
            ['name' => 'Spinach Salad with Apples and Eggs','foodcategory_id'=> 6],
            ['name' => 'Spunky Vegetable Pizza','foodcategory_id'=> 6],
            ['name' => 'Stir Fried Beef','foodcategory_id'=> 6],
            ['name' => 'Stir Fry Vegetables and Beef','foodcategory_id'=> 6],
            ['name' => 'Stir-Fry with Chicken and Noodles','foodcategory_id'=> 6],
            ['name' => 'Stove Top Casserole','foodcategory_id'=> 6],
            ['name' => 'Stove Top Green Chile Chicken Enchiladas','foodcategory_id'=> 6],
            ['name' => 'Stovetop Tamale Pie','foodcategory_id'=> 6],
            ['name' => 'Stuffed Bell Peppers','foodcategory_id'=> 6],
            ['name' => 'Stuffed Green Peppers','foodcategory_id'=> 6],
            ['name' => 'Stuffed Pasta Shells','foodcategory_id'=> 6],
            ['name' => 'Stuffed Summer Squash','foodcategory_id'=> 6],
            ['name' => 'Summer Vegetable Spaghetti','foodcategory_id'=> 6],

        ]);




    }
}
