<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insert sample data into foods table
        DB::table('foods')->insert([
        ['name' => 'Ambrosia','foodcategory_id'=> 1],
        ['name' => 'Avocado Black Bean Taquitos','foodcategory_id'=> 1],
        ['name' => 'Avocado Pita Pockets','foodcategory_id'=> 1],
        ['name' => 'Avocado Veggie Bake','foodcategory_id'=> 1],
        ['name' => 'Baked Cauliflower Tots','foodcategory_id'=> 1],
        ['name' => 'Baked Chicken Nuggets','foodcategory_id'=> 1],
        ['name' => 'Baked Tortilla Chips','foodcategory_id'=> 1],
        ['name' => 'Beet & White Bean Salad','foodcategory_id'=> 1],
        ['name' => 'Bell Pepper Nachos','foodcategory_id'=> 1],
        ['name' => 'Black Bean Salsa','foodcategory_id'=> 1],
        ['name' => 'Black Bean Soup','foodcategory_id'=> 1],
        ['name' => 'Broiled Tomatoes and Cheese','foodcategory_id'=> 1],
        ['name' => 'Celery with Apricot Blue Cheese Spread','foodcategory_id'=> 1],
        ['name' => 'Cherry, Melon, & Grape Salad','foodcategory_id'=> 1],
        ['name' => 'Chickpea Dip','foodcategory_id'=> 1],
        ['name' => 'Chili Bean Dip','foodcategory_id'=> 1],
        ['name' => 'Chilled Cantaloupe Soup','foodcategory_id'=> 1],
        ['name' => 'Chunky Garbanzo Bean Dip','foodcategory_id'=> 1],
        ['name' => 'Cookie Cutter Appetizers','foodcategory_id'=> 1],
        ['name' => 'Corn Toasties','foodcategory_id'=> 1],
        ['name' => 'Cowboy Caviar (Bean Salsa)','foodcategory_id'=> 1],
        ['name' => 'Creamy Dill Dip','foodcategory_id'=> 1],
        ['name' => 'Creamy Vegetable Dip','foodcategory_id'=> 1],
        ['name' => 'Crispy Taquitos','foodcategory_id'=> 1],
        ['name' => 'Crunchy Vegetable Wraps','foodcategory_id'=> 1],
        ['name' => 'Cucumber Blueberry Salad','foodcategory_id'=> 1],
        ['name' => 'Cucumber Yogurt and Cream Cheese Dip','foodcategory_id'=> 1],
        ['name' => 'Cucumber, Yogurt and Herb Dip','foodcategory_id'=> 1],
        ['name' => 'Curry Vegetable Dip','foodcategory_id'=> 1],
        ['name' => 'Dave’s Herb-Stuffed Mushrooms','foodcategory_id'=> 1],
        ['name' => 'Deviled Eggs','foodcategory_id'=> 1],
        ['name' => 'Fiesta Hummus','foodcategory_id'=> 1],
        ['name' => 'Fiesta Lettuce Wraps and Pepper Boats','foodcategory_id'=> 1],
        ['name' => 'Fiesta Rice Salad','foodcategory_id'=> 1],
        ['name' => 'Fiesta Stuffed Avocado','foodcategory_id'=> 1],
        ['name' => 'Fruit & Feta Salad','foodcategory_id'=> 1],
        ['name' => 'Fruit and Peanut Butter Dip','foodcategory_id'=> 1],
        ['name' => 'Fruit Salsa','foodcategory_id'=> 1],
        ['name' => 'Grape Salsa','foodcategory_id'=> 1],
        ['name' => 'Grilled Vegetables','foodcategory_id'=> 1],
        ['name' => 'Hummus','foodcategory_id'=> 1],
        ['name' => 'Layered Black Bean Dip','foodcategory_id'=> 1],
        ['name' => 'Mango Salsa','foodcategory_id'=> 1],
        ['name' => 'Manhattan Clam Chowder','foodcategory_id'=> 1],
        ['name' => 'Mini Caprese Bites','foodcategory_id'=> 1],
        ['name' => 'Mozz Totz','foodcategory_id'=> 1],
        ['name' => 'Orange Glazed Skinless Chicken Wings','foodcategory_id'=> 1],
        ['name' => 'Oven-Fried Yucca','foodcategory_id'=> 1],
        ['name' => 'Pea Guacamole','foodcategory_id'=> 1],
        ['name' => 'Pear Quesadillas','foodcategory_id'=> 1],
        ['name' => 'Potato Cakes','foodcategory_id'=> 1],
        ['name' => 'Potato Nachos','foodcategory_id'=> 1],
        ['name' => 'Potato Skins with Buffalo Chicken','foodcategory_id'=> 1],
        ['name' => 'Pupusas Revueltas','foodcategory_id'=> 1],
        ['name' => 'Quick and Easy Bean Dip','foodcategory_id'=> 1],
        ['name' => 'Sardine, Cucumber, and Tomato Sandwich','foodcategory_id'=> 1],
        ['name' => 'Soft Pretzels','foodcategory_id'=> 1],
        ['name' => 'Southwestern Pepper Cups','foodcategory_id'=> 1],
        ['name' => 'Summer Salad','foodcategory_id'=> 1],
        ['name' => 'Sunshine Salad','foodcategory_id'=> 1],
        ['name' => 'Sweet and Juicy Raisin Tapenade','foodcategory_id'=> 1],
        ['name' => 'Sweet and Savory Peanut Butter Dip','foodcategory_id'=> 1],
        ['name' => 'Teriyaki Lettuce Wraps','foodcategory_id'=> 1],
        ['name' => 'Tomato Basil and Bean Pasta Salad','foodcategory_id'=> 1],
        ['name' => 'Tomato Basil Bruschetta','foodcategory_id'=> 1],
        ['name' => 'Tortilla Chips and Bean Dip','foodcategory_id'=> 1],
        ['name' => 'Tuna Veggie Antipasto','foodcategory_id'=> 1],
        ['name' => 'Turkey Pinwheel Appetizers','foodcategory_id'=> 1],
        ['name' => 'Turnip Pancakes','foodcategory_id'=> 1],
        ['name' => 'Vegetable Medley with Salsa Dip','foodcategory_id'=> 1],
        ['name' => 'Vegetarian Stuffed Peppers','foodcategory_id'=> 1],
        ['name' => 'Veggie Quesadillas','foodcategory_id'=> 1],
        ['name' => 'Waldorf Salad','foodcategory_id'=> 1],
        ['name' => 'White Bean Bruschetta','foodcategory_id'=> 1],
        ['name' => 'Whole Wheat Garlic Bread Sticks','foodcategory_id'=> 1],
            ['name' => 'Avocado Melon Breakfast Smoothie','foodcategory_id'=> 2],
            ['name' => 'Batido (Smoothie)','foodcategory_id'=> 2],
            ['name' => 'Cafe Mocha','foodcategory_id'=> 2],
            ['name' => 'Cantaloupe Cooler','foodcategory_id'=> 2],
            ['name' => 'Coffee Cooler','foodcategory_id'=> 2],
            ['name' => 'Flavored Water','foodcategory_id'=> 2],
            ['name' => 'Fruit and Yogurt Breakfast Shake','foodcategory_id'=> 2],
            ['name' => 'Fruit Juice Slush','foodcategory_id'=> 2],
            ['name' => 'Fruit Milk Shakes','foodcategory_id'=> 2],
            ['name' => 'Fruit Slush','foodcategory_id'=> 2],
            ['name' => 'Fruit Smoothie','foodcategory_id'=> 2],
            ['name' => 'Lemonade','foodcategory_id'=> 2],
            ['name' => 'Mango Shake','foodcategory_id'=> 2],
            ['name' => 'Orange Banana Frosty','foodcategory_id'=> 2],
            ['name' => 'Orange Cow','foodcategory_id'=> 2],
            ['name' => 'Orange Delight Juice','foodcategory_id'=> 2],
            ['name' => 'Peach Cooler','foodcategory_id'=> 2],
            ['name' => 'Peanut Butter Banana Breakfast Shake','foodcategory_id'=> 2],
            ['name' => 'Peanut Butter Banana Smoothie','foodcategory_id'=> 2],
            ['name' => 'Purple Cow','foodcategory_id'=> 2],
            ['name' => 'Summer Breeze Smoothie','foodcategory_id'=> 2],
            ['name' => 'Very Berry Smoothie','foodcategory_id'=> 2],

            ['name' => 'Apple Oatmeal Muffins','foodcategory_id'=> 3],
            ['name' => 'Banaha Bread','foodcategory_id'=> 3],
            ['name' => 'Banana Berry Muffins','foodcategory_id'=> 3],
            ['name' => 'Banana Bread','foodcategory_id'=> 3],
            ['name' => 'Basic Muffins','foodcategory_id'=> 3],
            ['name' => 'Blue Corn Pan Bread','foodcategory_id'=> 3],
            ['name' => 'Blueberry Coffee Cake','foodcategory_id'=> 3],
            ['name' => 'Blueberry Muffins','foodcategory_id'=> 3],
            ['name' => 'Bran Flake Raisin Muffins','foodcategory_id'=> 3],
            ['name' => 'Bran Muffins','foodcategory_id'=> 3],
            ['name' => 'Bread in a Bag','foodcategory_id'=> 3],
            ['name' => 'Chapatis Flatbread','foodcategory_id'=> 3],
            ['name' => 'Cinnamon Sugared Pumpkin Pecan Muffins','foodcategory_id'=> 3],
            ['name' => 'Corn Bread','foodcategory_id'=> 3],
            ['name' => 'Corn Toasties','foodcategory_id'=> 3],
            ['name' => 'Corn Tortillas','foodcategory_id'=> 3],
            ['name' => 'Cornmeal Pancakes','foodcategory_id'=> 3],
            ['name' => 'Cranberry Nut Bread','foodcategory_id'=> 3],
            ['name' => 'Cranberry Pumpkin Muffins','foodcategory_id'=> 3],
            ['name' => 'Drop Biscuits (from Better Baking Mix)','foodcategory_id'=> 3],
            ['name' => 'Fabulous Fruit Muffins','foodcategory_id'=> 3],
            ['name' => 'Feather Rolls','foodcategory_id'=> 3],
            ['name' => 'Flour Tortillas','foodcategory_id'=> 3],
            ['name' => 'Garden Pan Bread','foodcategory_id'=> 3],
            ['name' => 'Ginger Bread Mix','foodcategory_id'=> 3],
            ['name' => 'Ginger Orange Muffins','foodcategory_id'=> 3],
            ['name' => 'Homemade Bagles','foodcategory_id'=> 3],
            ['name' => 'Homemade Pizza Crust','foodcategory_id'=> 3],
            ['name' => 'Homestyle Biscuits','foodcategory_id'=> 3],
            ['name' => 'Lemon Corn Cake','foodcategory_id'=> 3],
            ['name' => 'Mixed Grain Bread','foodcategory_id'=> 3],
            ['name' => 'Muffins (from Better Baking Mix)','foodcategory_id'=> 3],
            ['name' => 'Naan','foodcategory_id'=> 3],
            ['name' => 'Oat Bran Muffins','foodcategory_id'=> 3],
            ['name' => 'Oat Snack Cakes','foodcategory_id'=> 3],
            ['name' => 'Oatmeal Bread','foodcategory_id'=> 3],
            ['name' => 'Oatmeal Raisin Muffins','foodcategory_id'=> 3],
            ['name' => 'Parmesan Chive Biscuits','foodcategory_id'=> 3],
            ['name' => 'Peanut Butter Bread','foodcategory_id'=> 3],
            ['name' => 'Peanut Butter Muffins','foodcategory_id'=> 3],
            ['name' => 'Perfect Pumpkin Pancakes','foodcategory_id'=> 3],
            ['name' => 'Pumpkin Bread','foodcategory_id'=> 3],
            ['name' => 'Pumpkin Chocolate Muffins','foodcategory_id'=> 3],
            ['name' => 'Soft Pretzels','foodcategory_id'=> 3],
            ['name' => 'Soul-Healthy Cornbread','foodcategory_id'=> 3],
            ['name' => 'Three-Grain Peanut Bread','foodcategory_id'=> 3],
            ['name' => 'Whole Wheat Garlic Bread Sticks','foodcategory_id'=> 3],
            ['name' => 'Whole Wheat Muffins','foodcategory_id'=> 3],
            ['name' => 'Wild Rice Muffins','foodcategory_id'=> 3],
            ['name' => 'Zucchini Bread','foodcategory_id'=> 3],

            ['name' => 'Apple Oatmeal Muffins','foodcategory_id'=> 4],
['name' => 'Apple Sandwiches','foodcategory_id'=> 4],
['name' => 'Apple Slice Pancakes','foodcategory_id'=> 4],
['name' => 'Apple Wedges with Pumpkin Almond Butter','foodcategory_id'=> 4],
['name' => 'Applesauce Pancakes','foodcategory_id'=> 4],
['name' => 'Avocado Breakfast Bruschetta','foodcategory_id'=> 4],
['name' => 'Avocado Melon Breakfast Smoothie','foodcategory_id'=> 4],
['name' => 'Banana Berry Muffins','foodcategory_id'=> 4],
['name' => 'Banana Oatmeal Pancakes with Lentils','foodcategory_id'=> 4],
['name' => 'Banana Pancakes with Apple Topping','foodcategory_id'=> 4],
['name' => 'Banana Split Oatmeal','foodcategory_id'=> 4],
['name' => 'Banana Waldorf','foodcategory_id'=> 4],
['name' => 'Banana Walnut Oatmeal','foodcategory_id'=> 4],
['name' => 'Basic Quiche','foodcategory_id'=> 4],
['name' => 'Batido (Smoothie)','foodcategory_id'=> 4],
['name' => 'Bell Pepper and Vidalia Onion Strata with Fresh Salsa','foodcategory_id'=> 4],
['name' => 'Black Bean Burrito','foodcategory_id'=> 4],
['name' => 'Blue Cornmeal Pancakes','foodcategory_id'=> 4],
['name' => 'Blueberry Coffee Cake','foodcategory_id'=> 4],
['name' => 'Blueberry Muffins','foodcategory_id'=> 4],
['name' => 'Bran Flake Raisin Muffins','foodcategory_id'=> 4],
['name' => 'Bran Muffins','foodcategory_id'=> 4],
['name' => 'Breakfast Parfait','foodcategory_id'=> 4],
['name' => 'Broccoli Omelet','foodcategory_id'=> 4],
['name' => 'Broccoli-Cheddar Frittata','foodcategory_id'=> 4],
['name' => 'Buttermilk Scones','foodcategory_id'=> 4],
['name' => 'Cherry Puff Pancake','foodcategory_id'=> 4],
['name' => 'Cinnamon Sugared Pumpkin Pecan Muffins','foodcategory_id'=> 4],
['name' => 'Cinnamon-Raisin Breakfast Mix','foodcategory_id'=> 4],
['name' => 'Coffee Cooler','foodcategory_id'=> 4],
['name' => 'Corn Casserole','foodcategory_id'=> 4],
['name' => 'Cornmeal Pancakes','foodcategory_id'=> 4],
['name' => 'Cranberry Pumpkin Muffins','foodcategory_id'=> 4],
['name' => 'Crunchy Berry Parfait','foodcategory_id'=> 4],
['name' => 'Eggs over Kale and Sweet Potato Grits','foodcategory_id'=> 4],
['name' => 'Fabulous Fruit Muffins','foodcategory_id'=> 4],
['name' => 'Fantastic French Toast','foodcategory_id'=> 4],
['name' => 'Fruit and Yogurt Breakfast Shake','foodcategory_id'=> 4],
['name' => 'Fruit Pizza To Go','foodcategory_id'=> 4],
['name' => 'Fruit Smoothie','foodcategory_id'=> 4],
['name' => 'Fruit Snake','foodcategory_id'=> 4],
['name' => 'Fruit Yogurt Parfait','foodcategory_id'=> 4],
['name' => 'Fruity Homemade Oatmeal','foodcategory_id'=> 4],
['name' => 'Garden Frittata','foodcategory_id'=> 4],
['name' => 'Ginger Orange Muffins','foodcategory_id'=> 4],
['name' => 'Granola Bars','foodcategory_id'=> 4],
['name' => 'Granola with Oatmeal, Coconut, and Pecans','foodcategory_id'=> 4],
['name' => 'Green Onion Omelet','foodcategory_id'=> 4],
['name' => 'Herbed Spinach Quiche Portabella Caps','foodcategory_id'=> 4],
['name' => 'Homemade Bagles','foodcategory_id'=> 4],
['name' => 'Hot Cornmeal Cereal','foodcategory_id'=> 4],
['name' => 'Huevos Motuleños','foodcategory_id'=> 4],
['name' => 'Jean’s Banana Pudding Parfait','foodcategory_id'=> 4],
['name' => 'Jiffy Oatmeal Crunch','foodcategory_id'=> 4],
['name' => 'Light as a Feather Whole Wheat Pancakes','foodcategory_id'=> 4],
['name' => 'Melon and Mint','foodcategory_id'=> 4],
['name' => 'Microwave Denver Scramble Slider','foodcategory_id'=> 4],
['name' => 'Muffins (from Better Baking Mix)','foodcategory_id'=> 4],
['name' => 'No Bake Breakfast Cookies','foodcategory_id'=> 4],
['name' => 'Oat Bran Muffins','foodcategory_id'=> 4],
['name' => 'Oat Snack Cakes','foodcategory_id'=> 4],
['name' => 'Oatmeal Bread','foodcategory_id'=> 4],
['name' => 'Oatmeal Raisin Muffins','foodcategory_id'=> 4],
['name' => 'Overnight Oatmeal','foodcategory_id'=> 4],
['name' => 'Overnight Oatmeal with Berries','foodcategory_id'=> 4],
['name' => 'Pancakes (from Better Baking Mix)','foodcategory_id'=> 4],
['name' => 'Peanut Butter Banana Breakfast Shake','foodcategory_id'=> 4],
['name' => 'Peanut Butter Cereal Bars','foodcategory_id'=> 4],
['name' => 'Peanut Butter Muffins','foodcategory_id'=> 4],
['name' => 'Perfect Pumpkin Pancakes','foodcategory_id'=> 4],
['name' => 'Pumpkin Chocolate Muffins','foodcategory_id'=> 4],
['name' => 'Pumpkin Cookies','foodcategory_id'=> 4],
['name' => 'Quesadilla con Huevos','foodcategory_id'=> 4],
['name' => 'Rice Bowl Breakfast with Fruit and Nuts','foodcategory_id'=> 4],
['name' => 'Rise and Shine Cobbler','foodcategory_id'=> 4],
['name' => 'Spanish Omelet','foodcategory_id'=> 4],
['name' => 'Springtime Cereal','foodcategory_id'=> 4],
['name' => 'Strawberry and Banana Fruit Smoothie','foodcategory_id'=> 4],
['name' => 'Strawberry Banana Parfait','foodcategory_id'=> 4],
['name' => 'Strawberry Mango Feta Toast Points','foodcategory_id'=> 4],
['name' => 'Summer Breeze Smoothie','foodcategory_id'=> 4],
['name' => 'Sure to Please Baked Eggs & Cheese','foodcategory_id'=> 4],
['name' => 'Sweet Potato Hash with Egg','foodcategory_id'=> 4],
['name' => 'Sweet Potato Pancakes with Balsamic Maple Mushrooms','foodcategory_id'=> 4],
['name' => 'Tomato and Garlic Omelet','foodcategory_id'=> 4],
['name' => 'Tropical Morning Treat','foodcategory_id'=> 4],
['name' => 'Tropical Overnight Oatmeal','foodcategory_id'=> 4],
['name' => 'Veggie Omelet in a Mug','foodcategory_id'=> 4],
['name' => 'Very Berry Muesli','foodcategory_id'=> 4],
['name' => 'Very Berry Smoothie','foodcategory_id'=> 4],
['name' => 'Whole Grain Strawberry Pancakes','foodcategory_id'=> 4],
['name' => 'Whole Wheat Muffins','foodcategory_id'=> 4],
['name' => 'Wild Rice Muffins','foodcategory_id'=> 4],
['name' => 'Yogurt Berry Parfait','foodcategory_id'=> 4],





        ]);

        foreach (array_chunk($foods, 100) as $batch) {
            DB::table('foods')->insert($batch);
        }



    }
}
